### ISSUE TITLE
Purifier not extracting with Ender IO Item Conduits

### ISSUE THREAD

**Issue by DRTR0** [McJty/DeepResonance#100]
I can insert filter material just fine with an Item Conduit from Ender IO. But it doesn't want to extract spent filter material. I don't know what the issue is. I've tried redstone signal, active without redstone, always active, item filters, I've tried all sides of the purifier, etc. It does nothing but spit the spent material into the air. The only solution is to put a chest directly on the purifier, which looks ugly.

**Comment by McJty** [comment]
Spent filter material cannot be extracted as it is never stored in the purifier. It is ejected into an adjacent chest.
