### ISSUE TITLE
Tank having... interesting behavior

### ISSUE THREAD

**Issue by NoobFortress2** [McJty/DeepResonance#101]
I clicked with a bucket on a tank filled with lava, and the result was it giving me an entire inventory full of lava buckets...
I found this on version 1.9.4-1.2.0beta35

**Comment by McJty** [comment]
What version of MC?

**Comment by NoobFortress2** [comment]
1.10.2
this might be the cause :p

**Comment by McJty** [comment]
Should be fine. I'm using it with that too. I'll check this out later

**Comment by NoobFortress2** [comment]
this might not be deepresonance's fault, I'm getting a similar glitch with enderIO tanks. guessing something is messing up with fluids in general

**Comment by NoobFortress2** [comment]
aaaaand it fixed itself :P I literally did nothing and it no longer happens

**Comment by danneker** [comment]
I can confirm that this indeed happens. I can also confirm that this also happens with enderIO tanks and so I would also guess that it is not an error with deep resonance.

It seems to create 1000 buckets...maybe a mix up somewhere between milibuckets and buckets? 

Minecraft 1.10.2
Deep Resonance 1.9.4-1.2.0 beta 35
