### ISSUE TITLE
Pedestal's collector caching defunct?

### ISSUE THREAD

**Issue by Xandaros** [McJty/DeepResonance#103]
As far as I can tell, this [condition in the `findCollector` function](https://github.com/McJty/DeepResonance/blob/e074ccf0414c8d94c18c5c2fe93eae82d84e207b/src/main/java/mcjty/deepresonance/blocks/pedestal/PedestalTileEntity.java#L117) is never true:
```java
if (WorldHelper.getBlockAt(worldObj, crystalLocation) == EnergyCollectorSetup.energyCollectorBlock) {
```
I think it should read
```java
if (WorldHelper.getBlockAt(worldObj, cachedLocator) == EnergyCollectorSetup.energyCollectorBlock) {
```
instead.

**Comment by McJty** [comment]
You are right. Will fix this
