### ISSUE TITLE
Improvement: Need to shift right click to change insert/extract of tank face.

### ISSUE THREAD

**Issue by DRTR0** [McJty/DeepResonance#105]
There's no way to simply just right click a bucket of lava into the tank. You cannot shift right click with a bucket or it will place it next to or ontop of the tank. Is this an intended feature to not be able to simply right click buckets of lava in?

**Comment by McJty** [comment]
Right click of lava bucket in tank works just fine for me and everyone else that I have seen doing it. Not sure why it wouldn't work for you unless you have some other mod that changes how lava buckets work

**Comment by DRTR0** [comment]
If I right click the tank with a lava bucket in my hand, it does nothing but change the insert/extract. It doesn't do it for Ender IO tank. Perhaps because I was in creative mode? I'll test in Survival.
