### ISSUE TITLE
Console spam after the tank rewrite

### ISSUE THREAD

**Issue by Fey142** [McJty/DeepResonance#108]
Reference to https://github.com/McJty/DeepResonance/issues/68

After the rewrite this is what is happening now: http://pastebin.com/HzZs3YS1
Unlike before when it was in spikes it is now constant spam (2-3 TPS when I login and it crashes after a few moments due to the lag that accumulates - [13:06:52] [Server Watchdog/FATAL]: A single server tick took 60,00 seconds (should be max 0,05)
[13:06:52] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.)

Am I meant to break and replace the tanks or tinker with it in any way to fix the issue?

**Comment by Elec332** [comment]
Thats a high tank you have there
