### ISSUE TITLE
RFTools liquid monitor can no longer see the tank as "a tank"

### ISSUE THREAD

**Issue by Fey142** [McJty/DeepResonance#109]
Can no longer read the liquid inside like it used to - I have no idea who to "blame", but it was introduced with the tank rewrite.

Have a nice day and good job on the rewrite, works a lot better now.

**Comment by McJty** [comment]
Elec, is the tank no longer a proper fluid handler?

**Comment by McJty** [comment]
The problem is that IFluidHandler is no longer implemented by the tank TE

**Comment by McJty** [comment]
Fixed in RFTools. RFTools now properly supports the new capability system.
