### ISSUE TITLE
Minecraft crash DeepResonance error education on load crash report included

### ISSUE THREAD

**Issue by DanHolli123** [McJty/DeepResonance#110]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  MMFMLCorePlugin (MultiMine-1.10.2.jar)
  ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  LoadingPlugin (Quark-beta-50.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.225.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.47-beta.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 8/13/16 12:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: elec332/core/main/ElecCoreRegistrar
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:255)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: elec332/core/main/ElecCoreRegistrar
	at mcjty.deepresonance.DeepResonance.preInit(DeepResonance.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
	... 10 more
Caused by: java.lang.ClassNotFoundException: elec332.core.main.ElecCoreRegistrar
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.8.11
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 280274848 bytes (267 MB) / 785817600 bytes (749 MB) up to 3207856128 bytes (3059 MB)
	Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@49e23a55
	LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@706eb0a7
	LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@4708e337
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2056 Optifine OptiFine_1.10.2_HD_U_C2 123 mods loaded, 122 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2056.jar) 
	UCH	Forge{12.18.1.2056} [Minecraft Forge] (forge-1.10.2-12.18.1.2056.jar) 
	UCH	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCH	mysticalagriculture{1.1.3} [Mystical Agriculture] (mysticalagriculture-1.1.3.jar) 
	UCH	Squake{1.0.3} [Squake] (Squake-mc1.10.x-1.0.3.jar) 
	UCH	menumobs{1.5.1} [Menu Mobs] ([1.10]MenuMobs-universal-1.5.1.jar) 
	UCH	bettercombatmod{1.3.0} [Better Combat] ([MC_1.10.2]BetterCombat-1.3.4.jar) 
	UCH	JEI{3.8.0.240} [Just Enough Items] (jei_1.10.2-3.8.0.240.jar) 
	UCH	abyssalcraft{1.9.2.8} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.2.8.jar) 
	UCH	actuallyadditions{1.10.2-r50} [Actually Additions] (ActuallyAdditions-1.10.2-r50.jar) 
	UCH	antifrontview{1.1} [AntiFrontView] (AntiFrontView-1.1_MC1.9+.jar) 
	UCH	thedragoncore{1.1.0} [TheDragonCore] (thedragoncore-1.1.0.jar) 
	UCH	armorplus{1.10.2-6.0.0.1} [ArmorPlus] (armorplus-1.10.2-6.0.0.1.jar) 
	UCH	arrowcammod{2.2.0} [Arrow Cam Mod] (ArrowCamMod-1.10.2-2.2.0.jar) 
	UCH	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCH	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.2a.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCH	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.10.2.jar) 
	UCH	XaeroBetterPvP{1.10.2} [Better PVP Mod] (BetterPvP_1.10.2.1_Forge_1.10.2.jar) 
	UCH	BiomeTweaker{2.1.225} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.225.jar) 
	UCH	BiomesOPlenty{4.1.0.2065} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2065-universal.jar) 
	UCH	Bullseye{1.0.2} [Bullseye] (Bullseye-1.9.4-1.0.2.jar) 
	UCH	cavern{1.1.1} [Cavern] (Cavern_1.10-v1.1.1.jar) 
	UCH	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCH	CobbleDrops{1.10.2.01} [CobbleDrops] (CobbleDrops 1.10.2.01.jar) 
	UCH	cyclopscore{0.7.5} [Cyclops Core] (CyclopsCore-1.9.4-0.7.5.jar) 
	UCH	colossalchests{1.3.9} [Colossal Chests] (ColossalChests-1.9.4-1.3.9.jar) 
	UCH	compressedbonemeal{1.10.2} [Compressed Bonemeal] (compressedbonemeal-1.10.2.jar) 
	UCH	cosmeticarmorreworked{1.10.2-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v1.jar) 
	UCH	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
	UCH	covers{0.3.0.3} [Simple Covers] (covers-0.3.0.3-mc1.10.2.jar) 
	UCH	craftablehorsearmour{1.2} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.10.jar) 
	UCH	drones{1.10.2-1.2.0} [CustomDrones] (CustomDrones-1.2.0-mc1.10.2.jar) 
	UCH	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCH	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCE	deepresonance{1.2.1beta38} [DeepResonance] (deepresonance-1.10-1.2.1beta38.jar) 
	UCH	craftelytra{1.1} [Craftable Elytra] (ElytraCraft-1.1-1.10.2.jar) 
	UCH	endercore{1.10.2-0.4.1.47-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.47-beta.jar) 
	UCH	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.92_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.92_beta.jar) 
	UCH	enderutilities{0.6.5-beta.1} [Ender Utilities] (enderutilities-1.10.2-0.6.5-beta.1.jar) 
	UCH	endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
	UCH	ValkyrieLib{1.10-0.10.1} [Valkyrie Lib] (valkyrielib-1.10-0.10.1.jar) 
	UCH	EnvironmentalTech{1.10-0.10.1a} [Environmental Tech] (environmentaltech-1.10-0.10.1a.jar) 
	UCH	FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
	UCH	fluidconverters{2.0.3} [FluidConverters] (FluidConverters-1.9.4-2.0.3.jar) 
	UCH	SilentLib{1.0.11} [Silent Lib] (SilentLib-1.9.4-1.0.11-19.jar) 
	UCH	FunOres{1.2.7} [Fun Ores] (FunOres-1.10-1.2.7-68.jar) 
	UCH	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.10.2.jar) 
	UCH	geoactivity{2.2.3} [GeoActivity] (geoactivity-2.4.jar) 
	UCH	exp{1.1} [Exp Seedling Mod] (GiacomosExperienceSeedling1.9.4-1.1.jar) 
	UCH	fishing{1.4} [Fishing Net Mod] (GiacomosFishingNet1.9.4-1.4.jar) 
	UCH	grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.9.4-2.0.0-40.jar) 
	UCH	HoloInventory{2.0.0.130} [HoloInventory] (HoloInventory-1.9.4-2.0.0.130.jar) 
	UCH	immcraft{1.1.7} [Immersive Craft] (immcraft-1.9.4-1.1.7.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
	UCH	fyberbackpack{1.0.2} [Just Backpacks] (justbackpacks-mc1.9.4-1.0.2.jar) 
	UCH	jwin{univ_compat_filler} [Just What I Needed] (jwin-0.12.0_mc1.10.2.jar) 
	UCH	malisiscore{1.9.4-4.0.2} [MalisisCore] (malisiscore-1.9.4-4.0.2.jar) 
	UCH	malisisblocks{1.9.4-4.0.0} [Malisis Blocks] (malisisblocks-1.9.4-4.0.0.jar) 
	UCH	malisisdoors{1.9.4-5.0.1} [MalisisDoors] (malisisdoors-1.9.4-5.0.1.jar) 
	UCH	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCH	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCH	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCH	MoreFurnaces{1.8.1} [More Furnaces] (MoreFurnaces-1.10-1.8.1.jar) 
	UCH	Morphtool{1.0-6} [Morph-o-Tool] (Morph-o-Tool-1.0-6.jar) 
	UCH	MouseTweaks{2.6.3} [Mouse Tweaks] (MouseTweaks-2.6.3-mc1.9.4.jar) 
	UCH	AS_MultiMine{1.5.4} [Multi Mine] (MultiMine-1.10.2.jar) 
	UCH	MultiPageChest{1.7.0} [Multi Page Chest] (MultiPageChest-1.10-1.7.0.jar) 
	UCH	nethercore{1.10.2-2.0.2} [Nether Core] (nethercore-1.10.2-2.0.2.jar) 
	UCH	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCH	recipehandler{0.4} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.4(1.9).jar) 
	UCH	fodc{1.9.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.0.jar) 
	UCH	pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.10.2-1.5.0.jar) 
	UCH	progressiveautomation{1.6.48} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.48.jar) 
	UCH	reborncore{2.5.5.3} [RebornCore] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCH	QuantumStorage{3.1.0} [QuantumStorage] (QuantumStorage-1.9.4-3.1.0.jar) 
	UCH	Quark{beta-50} [Quark] (Quark-beta-50.jar) 
	UCH	rfpr{3.4.0} [Real First-Person Render] (Real First-Person Render-1.10.2-3.4.0.jar) 
	UCH	reborncore-mcmultipart{2.5.5.3} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCH	recycler{1.3} [Corail Recycleur] (recycler-1.3.1-1.9.4.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCH	refinedrelocation{@VERSION@} [Refined Relocation] (RefinedRelocation-mc1.10.2-2.0.8.jar) 
	UCH	regrowableleaves{1.10.2-3.1.2} [Regrowable Leaves] (regrowableleaves-1.10.2-3.1.2.jar) 
	UCH	rftl{1.0} [Rotten Flesh to Leather] (RFTL 1.0.jar) 
	UCH	scenter{1.10.2-3.8.0} [Scenter] (scenter-1.10.2-3.8.0.jar) 
	UCH	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCH	shouldersurfing{v1} [Shoulder Surfing] (ShoulderSurfing-1.10.2-1.1.jar) 
	UCH	substratum{1.6.0.1} [Substratum] (Substratum-1.10.2-1.6.0.1.jar) 
	UCH	supercraftingframe{1.2.0.85} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.0.85.jar) 
	UCH	superminer_core{[1.10.2]-2.1.0.022} [SuperMiner] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_captivator{[1.10.2]-2.1.0.022} [SuperMiner Captivator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_excavator{[1.10.2]-2.1.0.022} [SuperMiner Excavator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_illuminator{[1.10.2]-2.1.0.022} [SuperMiner Illuminator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_lumbinator{[1.10.2]-2.1.0.022} [SuperMiner Lumbinator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_shaftanator{[1.10.2]-2.1.0.022} [SuperMiner Shaftanator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_substitutor{[1.10.2]-2.1.0.022} [SuperMiner Substitutor] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	superminer_veinator{[1.10.2]-2.1.0.022} [SuperMiner Veinator] (SuperMiner-[1.10.2]-2.1.0.022.jar) 
	UCH	Tesla{1.2.0.38} [TESLA] (Tesla-1.10.2-1.2.0.38.jar) 
	UCH	TomsMod|Core{2.0.12} [Tom's Mod Core] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|Defense{2.0.12} [Tom's Mod Defense] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|Energy{2.0.12} [Tom's Mod Energy] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|Factory{2.0.12} [Tom's Mod Factory] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|Storage{2.0.12} [Tom's Mod Storage] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|Transport{2.0.12} [Tom's Mod Transport] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	TomsMod|WeaponsAndTools{2.0.12} [Tom's Mod Tools and Combat] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	MapWriterTm{2.0.12} [Map Writer in Tom's Mod] (TomsMod-2.0.12_ALPHA_MC-1.10.2.jar) 
	UCH	torcharrowsmod{1.10.2-1} [TorchArrowsMod] (torcharrows-1.10.2-1.jar) 
	UCH	Torcherino{4.0s} [Torcherino] (Torcherino-4.0s.jar) 
	UCH	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	visiblearmorslots{2.0} [Visible Armor Slots] (VisibleArmorSlots[1.10.2]-2.0.jar) 
	UCH	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCH	waterstrainer{1.1.0} [Water Strainer] (WaterStrainer-1.9.4-1.1.0.jar) 
	UCH	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.192.jar) 
	UCH	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.192.jar) 
	UCH	weaponsplus{1.9.4-3.0.0.0} [WeaponsPlus] (WeaponsPlus1.9.4-3.0.0.0.jar) 
	UCH	UniDict{1.10.2-1.4c} [UniDict] (UniDict-1.10.2-1.4c.jar) 
	UD	BiomeTweakerCore{2.1.225} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
MMFMLCorePlugin (MultiMine-1.10.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
LoadingPlugin (Quark-beta-50.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.225.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
  api.player.forge.PlayerAPITransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.47-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 12.0.1' Renderer: 'Mesa DRI Intel(R) Haswell Mobile '
	List of loaded APIs: 
		* AbyssalCraftAPI (1.8.1) from AbyssalCraft-1.10.2-1.9.2.8.jar
		* actuallyadditionsapi (17) from ActuallyAdditions-1.10.2-r50.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BiomeTweakerAPI (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* BiomeTweakerAPI|event (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* BiomeTweakerAPI|script|object (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* BiomeTweakerAPI|script|pack (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* BiomeTweakerAPI|script|wrapper (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* BiomeTweakerAPI|util (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* cavern.api (1.1.1) from Cavern_1.10-v1.1.1.jar
		* cavern.api.event (1.1.1) from Cavern_1.10-v1.1.1.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ActuallyAdditions-1.10.2-r50.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.48.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from EnderIO-1.10.2-3.0.1.92_beta.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.10-1.9.9.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.48.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.10-1.2.1beta38.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.92_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.92_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.92_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.92_beta.jar
		* environmentaltech.api (1.10-0.10.1a) from environmentaltech-1.10-0.10.1a.jar
		* FunOresAPI (3) from FunOres-1.10-1.2.7-68.jar
		* Guide-API|API (1.9.4-2.0.0-40) from Guide-API-1.9.4-2.0.0-40.jar
		* JustEnoughItemsAPI (4.1.0) from jei_1.10.2-3.8.0.240.jar
		* MapWriterApi (1.0.0) from TomsMod-2.0.12_ALPHA_MC-1.10.2.jar
		* McJtyLib (1.10-1.9.9) from mcjtylib-1.10-1.9.9.jar
		* reborncoreAPI (2.5.5.3) from RebornCore-1.10.2-2.5.5.3-universal.jar
		* RefinedRelocationAPI (2.0.0) from RefinedRelocation-mc1.10.2-2.0.8.jar
		* SuperScript (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* SuperScript|command (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* SuperScript|object (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* SuperScript|util (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
		* ValkyrieLib.api (1.10-0.10.1) from valkyrielib-1.10-0.10.1.jar
		* VeinMinerApi (0.3) from VeinMiner-0.34.1-1.9r571+73be663.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/danholli123/.minecraft/1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class

**Comment by McJty** [comment]
You must updated ElecCore

**Comment by DanHolli123** [comment]
@McJty crash on the menu no crash report available
exits game as though I pressed the quit button
happens every time

**Comment by McJty** [comment]
Well at that moment our mods are not yet active so that cannot have anything to do with this. In any case, even in that situation there should be a log somewhere in the logs folder.

**Comment by DanHolli123** [comment]
@McJty  when I deactivated the mod by changing '.jar' to '.jarx' it started just fine

**Comment by McJty** [comment]
You forgot to install ElecCore dependency

**Comment by DanHolli123** [comment]
after installing the dependency I did that

**Comment by McJty** [comment]
Without logs there is nothing that I can do. I know the mods work for other people. I use them myself.

**Comment by DanHolli123** [comment]
could be incompatibility with another mod
