### ISSUE TITLE
[1.10.2] [Mod Incompatibility] Journeymap

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/DeepResonance#112]
Journeymap believes that when in RFTools Dim I am overworld and start over righting the overworld map with the dim i am in.
![2016-08-24_02 01 25](https://cloud.githubusercontent.com/assets/11648771/17923752/323fb4ee-69d5-11e6-853c-e395df373ae1.png)

**Comment by McJty** [comment]
Why are you submitting this in the Deep Resonance tickets? Deep Resonance has nothing to do with dimensions. Also that looks like a bug in JourneyMap and not in rftools. I have no control over what journeymap renders. So two times wrong project

**Comment by Dijkstra1** [comment]
Sorry could have sworn I click on RFTools Dimensions, it just JourneyMap usually detects, what dim you are maps in accordingly. Again sorry for wrong project it was meant to go on RFTools Dimensions, if like I can open this issue there.

**Comment by McJty** [comment]
Well this is still a bug for JourneyMap. RFTools Dimension has no control over what journeymap renders. There is nothing I can do to fix it from my side. Has to be fixed in journeymap
