### ISSUE TITLE
Crash with new version of ElecCore

### ISSUE THREAD

**Issue by Susjin** [McJty/DeepResonance#124]
I just updated ElecCore to version 1.6.323, and the game crash on the startup

Log:
http://pastebin.com/4dQBHTpD

**Comment by Zhaulus** [comment]
Same error here https://www.dropbox.com/s/igmiwql9f74c6b6/fml-client-latest.log?dl=0

**Comment by Elec332** [comment]
This is a known issue, @McJty will upload the fix tomorrow

**Comment by McJty** [comment]
New version is on curse now
