### ISSUE TITLE
Server crash on chunk unload on latest version

### ISSUE THREAD

**Issue by SharkWipf** [McJty/DeepResonance#127]
Cross-posting from Elecs-Mods/ElecCore#58 because I don't know whether it is a problem on ElecCore's end or DeepResonance's end.
When unloading a chunk containing (presumably) Deep Resonance machines, the server crashes.

Running the latest versions of both Deep Resonance and ElecCore currently available through the Curse launcher, AKA 
deepresonance-1.10-1.2.9.jar 
and 
ElecCore-1.10.2-1.6.326.jar

Crash report: [Pastebin](http://pastebin.com/5uD8DSbc)

**Comment by iPencil** [comment]
Same thing happening here. After updating to the latest versions (same as the poster above) we are having a server crash everytime the DR chunk is unloaded.

**Comment by McJty** [comment]
Is this still an issue with latest ElecCore?

**Comment by SharkWipf** [comment]
Haven't been able to test yet because of the (now fixed) Elecs-Mods/ElecCore#62 crash. I'll be able to re-test this tomorrow afternoon at earliest, so unless someone else beats me to it I'll let you know by then

**Comment by iPencil** [comment]
We're updating in a few hours and I will be able to tell you then!

**Comment by SharkWipf** [comment]
Just tested, can confirm this issue is fixed now. Thanks!
