### ISSUE TITLE
required library (Eleccore) causing rendering issues with other mods

### ISSUE THREAD

**Issue by Saereth** [McJty/DeepResonance#133]
The ElecCore library required for deep resonance in 1.10.2 is breaking rendering of several other mods cause the items not to render at all (completely invisible). There is an open issue on the Eleccore github as well (https://github.com/Elecs-Mods/ElecCore/issues/67) but wanted to notify you additionally. Currently anyone wanting to use deep resonance and needing this library is subject to the render breaking in other mods.

**Comment by McJty** [comment]
What kind of rendering issues? Deep Resonance is in a lot of packs (FTB Infinity Lite, FTB HermitCraft, All The Mods, FTB Unstable) and nobody has ever reported rendering issues to me related to ElecCore. So what kind of render issue is this?

**Comment by HellFirePvP** [comment]
It's about the problem that his TEISR doesn't chain, it just calls super.renderByItem ... - which is bad if someone else already uses that same "hook" to render his things and then ElecCore just overwrites it. Details on the issue are added on ElecCore's issue that Saereth referenced.

**Comment by Elec332** [comment]
Has already been fixed
