### ISSUE TITLE
Why take ducts out?

### ISSUE THREAD

**Issue by KFGL** [McJty/DeepResonance#134]
Why did you take the ducts out.  As far as I can tell, they were still very useful, and very relevant.

**Comment by KFGL** [comment]
Maybe even necessary if you want a good power generator.

**Comment by McJty** [comment]
They never properly worked and other mods have good ducts as well

**Comment by Elec332** [comment]
I dont think they have ever been is a DR release, The code was largely there, but im quite sure the actual item has never been released.

**Comment by laserlemons** [comment]
Ducts would be nice. AFAIK there aren't any for 1.11 yet. (that work)
