### ISSUE TITLE
[ENHANCEMENT] Tank IFluidHandler Capability 

### ISSUE THREAD

**Issue by gigabit101** [McJty/DeepResonance#136]
Will it be possible for you to the IFluidHandler Capability to your tanks?
You can just use the wrapper if that's easier for you.

**Comment by McJty** [comment]
Deep Resonance already support IFluidHandler capability. In fact that's the only thing they support. The old system is no longer supported

**Comment by gigabit101** [comment]
you are using it I no but you are using it as a interface and not adding the Capability to the tile so other mods the use getCapability are not returning your tanks

**Comment by McJty** [comment]
The capability *is* added to the tile.

**Comment by McJty** [comment]
Check the code:

https://github.com/McJty/DeepResonance/blob/1.10/src/main/java/mcjty/deepresonance/blocks/tank/TileTank.java#L302

**Comment by gigabit101** [comment]
o0 so you only give it to it when the tank is in input and output mode
that's why I can access it with sfm

**Comment by McJty** [comment]
Does SFM actually support capabilities? Due to some other report I got I was under the impression it didn't.

Note that rftools control can access fluids in a DR tank by accessing it with side == null (i.e. not from any side). Can't SFM do that?

**Comment by gigabit101** [comment]
I have added the support for them it's not perfect but the you have the
only thank that dose not work with it yet this is my side and I will get it
fixed
