### ISSUE TITLE
RCL bug (version 1.10.2 - 1.3.0)

### ISSUE THREAD

**Issue by Valthan** [McJty/DeepResonance#137]
For some reason, the RCL refuses to enter a tank more than 300mb at a time. The smelter uses up 2 ores, then stops, leaving 200 mb in the tank above, then just stops. I've managed to get it to continue through the process but I have to deal with tiny increments of about 200 mb in a series of tanks separated by fluid conduits from EnderIO. The only way I managed to get 300mb inside is using the creative fluid injector and even that stops at 300. Even multiblocking several tanks together won't let it get past the 300mb limit.

Painstakingly getting it all the way through to the end of the process at the crystalizer is possible, but wasting resources at the laser section and very time consuming.

Interestingly, when multiblocked with three tanks and filled up, then broken, each tank section keeps 100mb, then refuses to be filled any further after that amount.

This leads me to believe that the RCL is refusing to mix with itself.

**Comment by McJty** [comment]
This is way to vague to do anything with. What exactly are you doing? What machines are connected? How are you transfering fluids?

**Comment by Valthan** [comment]
![2016-11-15_09 04 14](https://cloud.githubusercontent.com/assets/23480215/20312959/8f8b7d80-ab12-11e6-8f0f-e5941b8142f2.png)
![2016-11-15_09 04 18](https://cloud.githubusercontent.com/assets/23480215/20312961/90ffa9fc-ab12-11e6-88c0-9546a15eb4fe.png)
![2016-11-15_09 04 25](https://cloud.githubusercontent.com/assets/23480215/20312962/92413b0a-ab12-11e6-9d94-125f44800fb9.png)

Smelter to tank, direct transfer.

**Comment by McJty** [comment]
Can I get logs?

I have never seen this reported and I find it a bit confusing what is happening. Many people are using similar setups like that without issues

**Comment by Valthan** [comment]
[2016-11-15-6.log.gz](https://github.com/McJty/DeepResonance/files/592610/2016-11-15-6.log.gz)

**Comment by McJty** [comment]
What version of ElecCore?

**Comment by Valthan** [comment]
ElecCore-1.10.2-1.6.333.jar

**Comment by McJty** [comment]
There is nothing special in the log. No clue...

**Comment by Valthan** [comment]
Okay, so it's happening with the Purifier too. I made a line of multiblocked tanks to reach the Purifier, which then purified exactly 200mb of RCL then stopped, just like the Smelter did. When the Purifier took the 200mb from the tank above, the Smelter started back up, Smelted exactly 1 ore to produce 200mb, then stopped again.

![2016-11-15_10 20 45](https://cloud.githubusercontent.com/assets/23480215/20316047/92104166-ab1d-11e6-9a9f-15478eb93081.png)

**Comment by McJty** [comment]
nm. I can reproduce this...

**Comment by DaysofKnight** [comment]
Did we come to a fix for this? I'm having the same issue

**Comment by McJty** [comment]
@Elec332 will look at it. But he seems busy. For now the only thing you can do is rollback Deep Resonance *and* ElecCore at the same time

**Comment by DaysofKnight** [comment]
Yeah, rolling it back by one fixes the problem

**Comment by Tylian** [comment]
Chiming in to say I also have this bug.

**Comment by Rumpelstiltskinny** [comment]
after checking on my automated crystal production I see that I am also having similar issues...tanks not accepting more than 100mb RCL. This was not a problem until updating to DR 1.3.0 & EC 1.6.333, will attempt a rollback to deepresonance-1.10-1.2.9.jar & ElecCore-1.10.2-1.6.328.jar.

**Comment by McJty** [comment]
Was fixed in 1.3.1 and eleccore 345
