### ISSUE TITLE
[Issue] Waila compat conflict

### ISSUE THREAD

**Issue by accessdenied0** [McJty/DeepResonance#14]
Dear @McJty, 

I got this issue http://pastebin.com/YtDMUk4q with the newest update (0.2.0) and after trying different versions and combination of mods, I got the idea this mod could be the troublemaker.

Maybe I'm wrong but with 0.1.1 it works just fine and with 0.2.0 (with compat) it crashes.

access_denied

**Comment by nanakisan** [comment]
How did you come to that conclusion? Cause I don't see anything in that crash report mentioning Deep Resonance as the problem. However I do notice that you do not have mcjtylib-1.3.0.jar installed. Which is a required library file for all of McJty's mods.

**Comment by nanakisan** [comment]
I stand corrected it seems. It would appear that Deep Resonance has a hard dependency for Waila Compat. I wasl iterally starting up a test instance and this happened.  
  
http://paste.ee/p/RIgca

**Comment by McJty** [comment]
I don't really understand where this comes from. As far as I know we don't have a hard dependency on Waila Compat...

**Comment by nanakisan** [comment]
Yeah this is weird and it still crashed even when I had Waila installed.

**Comment by Elec332** [comment]
Im currently investigating this
