### ISSUE TITLE
my deep resonance smelter stops after one cycle

### ISSUE THREAD

**Issue by alphabox2310** [McJty/DeepResonance#142]
I have a tank under it with 50% full of lava, enough RF going into it and a tank above.  When I place some roe into it, it smelts one block, outputs the RCL into the top tank and then stops.

I have broken and remade all items twice. Tried different placement configurations and locations.
Nothing seems to work. Can you give me a hint where to look to fix this?

**Comment by McJty** [comment]
Already fixed in 1.3.1. This is a known bug in 1.3.0
