### ISSUE TITLE
Laser + Nether Star only gets a ~7% gain on efficiency and strength  

### ISSUE THREAD

**Issue by yoloswagginsyo** [McJty/DeepResonance#143]
Both in the manual in game, on the infusing laser and on the wiki it says the nether star should decrease purity by 60%, and increase efficiency and strength by 90%, instead it only increases by 7%, is this an unannounced change or bug? I have replicated it both on the server I'm playing on and in a creative world.

**Comment by McJty** [comment]
The 90% increase is for 500mb. If you have more in your tank it will be mixed with what is already there. For example, say you have a tank with 1000mb of 10% strength. One nether star will essentially take out 500mb, infuse that to 100% and then mix that back. So end result is 1000mb of 55% (100+10%).

Does that help?
