### ISSUE TITLE
Nether Portal Error

### ISSUE THREAD

**Issue by katur239** [McJty/DeepResonance#146]
Using:
Minecraft 1.10.2
Forge 2171
CompatLayer 0.0.33 Alpha
McJtyLib 2.2.0alpha11
DeepResonance 1.3.1alpha2

Nether Portal will not create and just leaves a fire. Throws this error in console:

>Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@1f2f86e:
java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres(Ljava/lang/String;)Lnet/minecraft/util/NonNullList;
    at mcjty.deepresonance.radiation.RadiationShieldRegistry.getLeadBlocks(RadiationShieldRegistry.java:25) ~[RadiationShieldRegistry.class:?]

Full Error: http://pastebin.com/QXjYDzTd

Works okay on pre-compatlayer release.

I have also seen this RadiationShieldRegistry error in Mekanism Digital Miner ticks once, had to have forge delete the miner to load the world.

**Comment by katur239** [comment]
Here is the Mekanism Digital Miner crash log with same calls.

http://pastebin.com/Kjf0ceDF

**Comment by McJty** [comment]
Will be fixed in the release later today
