### ISSUE TITLE
Texture error with Tank configuration (1.4.0)

### ISSUE THREAD

**Issue by Franckyi** [McJty/DeepResonance#148]
The `Mode : none` side looks good, but when I configure it to `Mode : accept` or `Mode : provide`, [it looks like this](http://puu.sh/sF5ka/9a0555d126.jpg). I'm using the latest version (1.4.0).

**Comment by McJty** [comment]
On 1.10 or 1.11?

**Comment by Franckyi** [comment]
1.10

**Comment by McJty** [comment]
Fixed next release
