### ISSUE TITLE
Laser is not... Lasering

### ISSUE THREAD

**Issue by popp199** [McJty/DeepResonance#149]
So far I've tried in multiplayer(survival) and in single player(with creative). No matter which way I have everything facing the Laser will not turn on. I've tried several different catalysts. I've created a new world too, and nothing. 
Currently running Direwolf20 1.10 pack
![4697ec96d3ce5ffae5249a1bd864ee91](https://cloud.githubusercontent.com/assets/1548918/20900165/41a40058-bafb-11e6-8fbf-a83eaa09b310.png)
![0d682e4c52d2cfba35edf2d4448059c6](https://cloud.githubusercontent.com/assets/1548918/20900164/41a165b4-bafb-11e6-8b05-8b09b6d0daf0.png)

**Comment by McJty** [comment]
The laser is one block too far from the lens

**Comment by popp199** [comment]
Well that's embarrassing. Tutorial I watched didn't state the distance nor did I notice that in the wiki. It works. Thanks.
