### ISSUE TITLE
[1.11]Weird bugs in DeepResonance Tanks

### ISSUE THREAD

**Issue by Myknakryu** [McJty/DeepResonance#154]
Minecraft version: 1.11
Forge version:1.11 2188 and 1.11 2189
ElecCore version: 1.11 1.6.259
CompatLayer version: 1.11 0.1.3
McJtyLib version: 1,1x 2.3.1
DeepResonance version: 1.1x 1.4.1

So for few weeks i've been playing on minecraft 1.11 with mods. I hoped that it would be fixed eventually that i won't have to write bug report but it didn't (at least i've made tons of fuel for Actually additions with this method). Bug duplicates liquid that was poured into tank. Dropping it and picking bucket makes duplicated bucket of liquid. Also i've found out that some of tank models are broken.

From forge 2188
https://youtu.be/GxvkNsRRNyE

From forge 2189 with other mods.
https://youtu.be/wt5UO45xat8

**Comment by McJty** [comment]
Ok I'll check it out. Probably a stupid mistake in compatlayer

**Comment by McJty** [comment]
Fixed in the upcoming release of compatlayer (0.1.4)
