### ISSUE TITLE
wont let me use it

### ISSUE THREAD

**Issue by INVALID000** [McJty/DeepResonance#155]
it says im missinng compatlayer 1.01 or something

**Comment by McJty** [comment]
Yes, then download that. It is also on curse

**Comment by NightKev** [comment]
You should mention it as a dependency on the DR mod page then.

**Comment by laserlemons** [comment]
It's listed as a required library at the bottom of the download page.
https://minecraft.curseforge.com/projects/deep-resonance/files/2353328

**Comment by Carnaxus** [comment]
It's no longer mentioned but still required.

**Comment by McJty** [comment]
It is still mentioned there
