### ISSUE TITLE
[Feature Request] Radiation Monitor for use in Item Frame

### ISSUE THREAD

**Issue by cinimodaz** [McJty/DeepResonance#157]
Would be kind of cool if we could hang the radiation monitor in an item frame and it still register. Could work as a room monitor instead of just on the person.

**Comment by McJty** [comment]
Did you try it? That actually works already

**Comment by cinimodaz** [comment]
Hmm when I hang it on the wall it does not give me a number when I hover over it. I also don't see it change. I wonder what i am doing wrong?

**Comment by McJty** [comment]
Is there actually radiation around? Maybe show a few screenshots?

**Comment by cinimodaz** [comment]
Ok, so here are a few screenshots. Keep in mind this also shows that I am taking dmg and hunger from radiation even though I am blocked by 6 layers of dense glass and 2 layers of dense obsidian, however that is not the issue you will also see the screenshots of me mousing over the radiation monitor and no overlay coming up.
![2016-12-19_06 41 39](https://cloud.githubusercontent.com/assets/9374138/21311731/ca958d6c-c5b6-11e6-8566-3de4c12b9c75.png)
![2016-12-19_06 37 35](https://cloud.githubusercontent.com/assets/9374138/21311730/ca9464f0-c5b6-11e6-8d48-ffeb85da2f1a.png)
![2016-12-19_06 37 44](https://cloud.githubusercontent.com/assets/9374138/21311733/caa04554-c5b6-11e6-93c4-5f53d6912c44.png)
![2016-12-19_06 37 54](https://cloud.githubusercontent.com/assets/9374138/21311732/ca9f2750-c5b6-11e6-9890-0060ac399155.png)

**Comment by cinimodaz** [comment]
Forgot 3
![2016-12-19_06 47 17](https://cloud.githubusercontent.com/assets/9374138/21311790/13e074aa-c5b7-11e6-986b-8a6b1a5a99ac.png)
![2016-12-19_06 47 04](https://cloud.githubusercontent.com/assets/9374138/21311791/13e32b32-c5b7-11e6-8ca1-69b971cd2226.png)
![2016-12-19_06 47 07](https://cloud.githubusercontent.com/assets/9374138/21311792/13e68458-c5b7-11e6-94eb-354e3b8cfd4b.png)


 screenshots the ones with radiation.

**Comment by cinimodaz** [comment]
Are these enough of screenshots for you?

**Comment by McJty** [comment]
yes that's fine. I'll check this out later. This used to work for me. Not sure what changed
