### ISSUE TITLE
Crash when placing down the smelter

### ISSUE THREAD

**Issue by Professorvennie** [McJty/DeepResonance#158]
We are running the all the mods modpack with the latest version of deep Resonance(1.1x-1.4.1).  A member crafted the smelter and placed down the block and it crashed the server.
Log: http://pastebin.com/fnAkuywF

If you need any other information just let me know.

**Comment by McJty** [comment]
Do you have sponge?

**Comment by Professorvennie** [comment]
No we do not.

**Comment by McJty** [comment]
Very weird. I don't understand why this is happening. Is this reproducable or was it a one-time occurance?

**Comment by McJty** [comment]
Lack of information
