### ISSUE TITLE
Error executing task, ArithmeticException: / by zero

### ISSUE THREAD

**Issue by FiveEYZ** [McJty/DeepResonance#159]
Noticed this error in my latest.log

[error from latest.log](https://gist.github.com/FiveEYZ/1ffefaefc63f89e35ec678ecbfaaaa92)

should i be concerned? :)

Running direwolf20 1.10 containing:
deepresonance-1.1x-1.4.1
mcjtylib-1.1x-2.3.1
forge-1.10.2-12.18.3.2185-universal

also have this in the mix:
spongeforge-1.10.2-2171-5.1.0-BETA-2009

**Comment by McJty** [comment]
Might be a sponge bug. Did you try updating relevant mods and see if that helps?

**Comment by McJty** [comment]
Lack of information
