### ISSUE TITLE
Crystals not generating with 0.2.2

### ISSUE THREAD

**Issue by Thiana** [McJty/DeepResonance#16]
The natural crystals don't appear to be generating with 0.2.2.

To reproduce, create a new instance with ElecCore 1.4..130, Deep Resonance 0.2.2, Thermal Foundation 1.2.0-102, CoFHCore 3.0.4B1-308. Then use cofh clearblocks on a large area (I used 256x256) to remove water/lava/stone/sand/gravel. You'll see the standard ores, cofh ores and the DR ore but no crystals at all.

Thanks.

**Comment by McJty** [comment]
Actually they do generate but they are very rare. I just did the same test as you but instead I did: /cofh clearblocks McJty 256 256 256 deepresonance:resonatingCrystalBlock and it cleared a few.

**Comment by Thiana** [comment]
Using your command I found a single crystal in the area. 1 crystal in 256 chunks? I'm sure part of that is just bad RNG, but if this mod is supposed to be an option for early game power maybe you should increase the default spawn rate a bit?

**Comment by McJty** [comment]
Yes I will probably increase it somewhat.

**Comment by Elec332** [comment]
IIRC, this can be changed in the configs, right?

**Comment by McJty** [comment]
yes indeed. But I'll also increase the default
