### ISSUE TITLE
Crystals indicating refinement past 100% purity, invalid character in place of Strength, Efficiency

### ISSUE THREAD

**Issue by akirasoft** [McJty/DeepResonance#164]
Please see the attached screenshot. The valve was not allowing any liquids through when set to filter at 100% which caused some liquids to refine past a 100% purity. Some sort of ceiling issue perhaps?
![untitled](https://cloud.githubusercontent.com/assets/331226/21769191/1704542a-d643-11e6-8454-d00bbfb78644.png)

**Comment by McJty** [comment]
More info please? Version of MC? Version of Deep Resonance? ElecCore?

**Comment by akirasoft** [comment]
Sorry for that! 

ElecCore: 1.10.2-1.6.360

McjtyLib 1.1x-2.3.10

Deep Resonance 1.1.x-1.4.2

The One Probe 1.10-1.3.3

Minecraft 1.10.2, forge 12.18.3.2185

**Comment by McJty** [comment]
Was the crystal generated with those versions? How was the liquid before you generated a crystal from this?

**Comment by akirasoft** [comment]
Liquid was showing the same bizarre values in the post-purification step. I will collect more screenshots,

**Comment by McJty** [comment]
It is possible that your version of ElecCore is too old. There were some fixes in that mod

**Comment by McJty** [comment]
But for the already generated crystals it is possibly too late

**Comment by akirasoft** [comment]
They started out generating just fine, I even got some 100/100/100 crystals. Then I left the area chunkloaded and came back and it got all broken. I'm just messing around with this so I have no issues blowing up the existing crystals (it is just a game afterall!)

Looks like things are starting off during the ore smelting phase with a bonkers value now:
![oresmelting](https://cloud.githubusercontent.com/assets/331226/21769768/036910b0-d646-11e6-9463-cc896d2eb6ef.png)

and then it is getting purified into an even higher value: 
![purification](https://cloud.githubusercontent.com/assets/331226/21769806/249140be-d646-11e6-99f2-ccd982635897.png)

**Comment by akirasoft** [comment]
I'll update my eleccore and try again. It takes about 2-3 days of chunkloaded processing to get to this point (which is why I'm thinking there might be some sort of overflow issue here?)

**Comment by McJty** [comment]
It should not allow overflow so that seems unlikely

**Comment by akirasoft** [comment]
I think what causes this is when I set valve to only allow 100% strength/efficiency through it never allows anything to pass... (Maybe things never actually get to 100% due to floating point values?) In order to prevent the lasers from destroying my liquid crystal I was running one nether star and multiple emerald lasers against the fluid than over time all the tanks showed weird values.

**Comment by McJty** [comment]
It is possible that they never get to 100% yes. But that shouldn't cause these corrupt numbers. Then the fluid should simply not pass

**Comment by akirasoft** [comment]
Blew up all the tanks/valves Updated to ElecCore 1.10.2-1.6.379 and started smelting ore again and recreated the issue with corrupt values for strength and efficiency when I had emerald lasers and purifiers working together on the same set of tanks.

Blew everything up again and have not enabled the emerald lasers on my first set of purification tanks going to see if the fluid can pass through my refinement steps properly.

**Comment by akirasoft** [comment]
once I cleared out my entire setup to get rid of any crystal fluid that had been generated with the old version of ElecCore I did not see any more crystal get generated with purities over 100%. Closing out the issue, thanks for the help.
