### ISSUE TITLE
Crash upon putting lava into crystaliser's tank.

### ISSUE THREAD

**Issue by VeloxAzo** [McJty/DeepResonance#169]
Crystallizer tank was empty, put one bucket of lava inside while the crystalizer had some progress set. Save now crashes on startup. Singleplayer. Crashed the second the lava entered the tank. 

http://pastebin.com/Z6AJ8Npj

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Will be fixed next release
