### ISSUE TITLE
Server side crash on right clicking a Smelter

### ISSUE THREAD

**Issue by trienow** [McJty/DeepResonance#173]
# What was done
I right-clicked the Smelter.
This is the setup:
![screenshot_1](https://cloud.githubusercontent.com/assets/8478950/22610176/7eccfbcc-ea64-11e6-941e-70515d963676.png)
# What was the result
The server crashed, the clients did not.
[Cash Report Gist](https://gist.github.com/trienow/cb7f2a7ddf1760f3212cad4833e35b68#file-crash-2017-02-03_22-45-03-server-java)
# Versions
|   Software    |       Version       |
|---------------|---------------------|
| Minecraft     | 1.10.2              |
| Forge         | 12.18.3.2185        |
| DeepResonance | 1.1x-1.4.4          |
| ElecCore      | 1.6.379             |
| mcjtylib      | 1.10-2.2.0-SNAPSHOT |
| mcjtylib_ng   | 1.1x-2.3.5-SNAPSHOT |
| compatlayer   | 1.10-0.1.7          |

Thanks :)

**Comment by McJty** [comment]
You can't have both mcjtylib and mcjtylib_ng. Remove mcjtylib
