### ISSUE TITLE
Crash on server startup: IllegalArgumentException

### ISSUE THREAD

**Issue by KlutzLament** [McJty/DeepResonance#174]
I'm getting a crash with the message: `java.lang.IllegalArgumentException: bound must be positive` every time I try to start a server. I was able to reproduce it with just Deep Resonance and its dependencies installed.

Crash log: http://pastebin.com/g3vHgdpN

Mods:
compatlayer - 1.10-0.2.1
deepresonance - 1.1x-1.4.5
ElecCore - 1.10.2-1.6.379
mcjtylib - 1.1x-2.3.6
forge - 1.10.2-12.18.3.2185

**Comment by McJty** [comment]
Did you change Deep Resonance configs? In particular oregen?

**Comment by KlutzLament** [comment]
Actually, yes. I had `I:maxVeinSize`and `I:minVeinSize` set to the same value. I set them to different values and it stopped crashing.

**Comment by McJty** [comment]
Ok, mystery solved then. I'll see if I can make it a bit more robust

**Comment by McJty** [comment]
Actually the calculation of the vein size was totally wrong. Fixed next release
