### ISSUE TITLE
Tanks forgetting connections to EIO on reload

### ISSUE THREAD

**Issue by theunkn0wn1** [McJty/DeepResonance#176]
**Summery:**
Every time i unload a world, such as quitting the game, then reload it EIO does not reattach to DeepResonance tanks until i change the input\output mode of one of the tank's faces.

------------------
**Issue:** 
DR tanks are rendered defunct to anything other than DR blocks after world reload until manually reset.
Other DR blocks, such as Smelters, are seemingly unaffected.

-------------------
**Steps to reproduce:**

1.  Get two empty DR tanks, either crafted or obtained by other means
2. Place the two tanks vertically, with at least 1 block space between them
3. place a fluid conduit from EIO as to bridge the divide
4. set the Input/output mode of the tanks via right-clicking with empty hand
5. quit to title
a.or restart Minecraft, makes no difference
6. Reload world, observe
a. This occurs regardless to if the world was freshly generated or existing.

-----------------
**Useful information:**
DR version **1.1x-1.4.5** built against 1.11/ 0254505c4d2d063fecbb6846d5134c09e2b6e243
mcjtylib version**1.1x-2.3.7.jar** (from Curse)
EnderIO version **1.10.2-3.1.168** (from Curse)
Minecraft version **1.10.2**
Forge Version **12.18.3.2221**

**Comment by McJty** [comment]
It is possible that this bug will be fixed next release
