### ISSUE TITLE
Can't scoop up fluids from a tank when using stacked buckets

### ISSUE THREAD

**Issue by ShelLuser** [McJty/DeepResonance#178]
Hi there!

Using the latest Minecraft Forge (forge-1.11.2-13.20.0.2228) together with the latest Deep Resonance version (deepresonance-1.1x-1.4.5). The issue is simple: when there's fluid in a tank then trying to scoop this up using stacked buckets always fails. There is a scoop movement but nothing happens. But the moment you unstack them and use a single bucket then it'll work and you get the bucket + the fluid.

I believe this to be a bug because vanilla Minecraft mechanics normally allow for this (grab a bunch of buckets, scoop up lava and the filled bucket gets placed inside your inventory while the amount of stacked buckets decreases).

Minor issue but figured I should still report it, hope this helps!

**Comment by McJty** [comment]
Fixed next release
