### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DestinyPlayer** [McJty/DeepResonance#18]
There seems to be a problem with running Deep Resonance on the server. As in, it crashes it.
The crash log:
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/Deep%20Resonance%20crash-2015-10-04_16.10.52-server.txt
The normal log:
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/Deep%20Resonance%20Log.log

**Comment by Elec332** [comment]
This is known bug, and this has been fixed, though im not sure if @McJty has published this version yet

**Comment by McJty** [comment]
I will release a new version later today
