### ISSUE TITLE
[1.10.2] Wrong ElecCore Version

### ISSUE THREAD

**Issue by DestinyPlayer** [McJty/DeepResonance#180]
Forge - 12.18.3.2239
Deep Resonance is 1.1x-1.4.5
ElecCore is 1.10.2-1.7.402
Crash Log - http://pastebin.com/YrUuQXiY

Not sure why is this happening, but this is happening.

**Comment by Mattsingen** [comment]
I can confirm this.

**Comment by TheUnderTaker11** [comment]
Downgrade your ElecCore, that is what I did and it works fine

**Comment by Elec332** [comment]
ElecCore version 1.7.404 works
