### ISSUE TITLE
Duplicate item name with RFTools

### ISSUE THREAD

**Issue by mallrat208** [McJty/DeepResonance#181]
This isn't really a bug so much as an unfortunate choice in names.

RFTools and Deep Resonance both have an item called a 'Machine Frame' To add to that both blocks look visually similar with the minor difference that one of them has very faint lines on the top that the other doesn't.

Neither blocks are interchangeable and both have completely different recipes.

In short, it's confusing.

I feels like one of them be renamed or at the very least have a slightly different name. For example the one in DR could be a 'Resonating Machine Frame' since it's crafted with the Resonating Plates

**Comment by McJty** [comment]
Fixed next release
