### ISSUE TITLE
Wodlgen Configuration request

### ISSUE THREAD

**Issue by bookerthegeek** [McJty/DeepResonance#182]
Heyo!

Can we please maybe have a config to specify which dimensions World generation happens in? Specifically would like to enable only in the nether.

p.s. Yes, it is spelled that way in the configs

**Comment by McJty** [comment]
That will require nether variant of this ore (cobble stone based ore looks weird in the nether). But I'll implement it

**Comment by McJty** [comment]
Implemented next release. Nether ore is enabled by default but you can configure it. you can also disable generation in the overworld.
In addition crystals now also spawn in the nether

**Comment by bookerthegeek** [comment]
Thank you. I look forward to our robot overloards.
