### ISSUE TITLE
Possible issue with RF-API install check.

### ISSUE THREAD

**Issue by SiNevesh** [McJty/DeepResonance#183]
I am running a modpack with many mods, including Ender IO and Mekanism. Due to some issues I was manually modifying the pack, and it seems that Deep Resonance prioritises checking for the CoFH API within Mekanism (and possibly Ender IO) over actually checking for CoFH Core first.

I tried to load while having a version of Mekanism installed which had CoFH deleted, and Deep told me to have CoFH Core, Ender IO or Mekanism installed. I had both CoFH Core and Ender IO with CoFH within it, but until I installed a fresh Mekanism with CoFH contained, Minecraft would not launch, due to Deep being picky.

I thought I would mention it, as it might be a simple issue of not checking for CoFH Core prior to checking for other mods, as CoFH should take priority. 

Could also have been a fluke or user error though, so anyway. Have a good day!

**Comment by McJty** [comment]
Versions?

Anyway I don't think I actually care where cofh comes from. But you didn't tell me what actually went wrong

**Comment by SiNevesh** [comment]
My bad. I guess there isn't much point but I'll clarify anyway.

Deep Resonance was crashing Minecraft on launch due to not finding the CoFH API, even though I had CoFHCore-1.10.2-4.0.0.127-universal installed. Deep Resonance then says to make sure to have CoFH Core or a mod with the CoFH API "such as Ender IO, Mekanism, Etc" installed. The issue is of course that I have CoFH Core installed, but Deep Resonance was obviously trying to draw from Mekanism (or possibly, though very unlikely, a different mod). Due to trying to troubleshoot an issue with the collection of mods I was using I had deleted the CoFH API from inside the Mekanism jar file. The Deep Resonance crash was fixed once I updated, and thus "repaired" my Mekanism jar file.

I first used deepresonance-1.1x-1.4.2, then deepresonance-1.1x-1.4.6. Both of which acted the same way. The Mekanism version was 1.10.2-9.2.1.295 with a deleted CoFH folder, which I then updated to Mekanism-1.10.2-9.2.1.298 with everything packaged as normal. 

I am pretty sure that it's just an issue of priority on which mods Deep Resonance is trying to get CoFH from, as it was fixed once I repaired my Mekanism file, thereby giving Deep Resonance a version of the CoFH API to draw from apart from the other two (at least) I had installed. I would think it's more logical to get CoFH from the source mod, not a 3rd party mod, but do what you will. Or if the API is not found in one mod, skip to the next and find it there. 

From what I can tell you have it set to check for the API something like this:
**1.** Deep checks for API in Mekanism... not found, game crashes.
What I meant earlier was surely it would make more sense to run it more along the lines of:
**1.** Deep checks for API in CoFHCore... CoFHCore not installed _(for example)_, moving to next entry.
**2.** Deep checks for API in Mekanism... No API found in Mekanism, moving to next entry.
**3.** Deep checks for API in Ender IO... API found, continuing launch.

I don't pretend to know what coding Minecraft mods is like but I brought it up since it was the only mod hindering me from launching the game, seemingly from something that sounds easy to fix to my amateur point of view. And it's the kind of thing I would appreciate being notified of myself.

But anyway, sorry for bothering. It's a fringe case, I'll just not bother next time. Have a good day.

**Comment by Elec332** [comment]
DeepResonance does not care which mod carries the API, you can even throw in a Jar with just the COFH enegry API, and DeepResonance will detect it. This has most likely been a conflict with the API version in CoFHCore and Mekanism, causing it to not get loaded in the API registry.

DeepResonance just runs the 'isAPILoaded("CoFHAPI|energy")' check to verify it has been installed
