### ISSUE TITLE
Crystal Power goes above 100%

### ISSUE THREAD

**Issue by evanjohnman** [McJty/DeepResonance#185]
## Randomly generated crystals in the Nether can generate with over 100% power.

Example:
![2017-03-13_16 32 06](https://cloud.githubusercontent.com/assets/8527287/23929617/fc9ab250-08ec-11e7-835a-b4618dfd2dfb.png)

![2017-03-13_16 32 33](https://cloud.githubusercontent.com/assets/8527287/23929564/bfc6e5d8-08ec-11e7-8f61-67c6bbd21e14.png)

I believe it's due to the increased power multiplier at [DeepWorldGenerator](https://github.com/McJty/DeepResonance/blob/1.11/src/main/java/mcjty/deepresonance/worldgen/DeepWorldGenerator.java#L73).
[This line](https://github.com/McJty/DeepResonance/blob/1.11/src/main/java/mcjty/deepresonance/blocks/crystals/ResonatingCrystalTileEntity.java#L241) in ResonatingCrystalTileEntity is likely related. 

Any random.nextFloat() that generates above .33 will give this result.

This is not game-breaking. Generators will still drain the crystal as normal.

**Comment by McJty** [comment]
Will check it out

**Comment by McJty** [comment]
Fixed next release
