### ISSUE TITLE
Mekanism - Deep resonance - might just be me that is a derp

### ISSUE THREAD

**Issue by Dustmuz** [McJty/DeepResonance#191]
I'm running FTB beyond 1.5.3 - MC version 1.10

i've added Mekanism to the pack. 
but heres the "problem"

i have a generator with 2 crystals (gives 26K RF/tick (13 each)
my setup is 8 generator blocks, connected in a 2x2x2 pattern.
when i hook up an Ultimate universal cable (which can transfer 128K RF/tick) 
the generator cant "push" the energy out.
even if i connect the universal cable to the 4 bottom blocks, it still cant transfer the energy out of the generator "fast" enough. 

if i use EIO ender energy conduits, i can do it with 2 connections. 

is this a "problem" between Mekanism and Deep resonance?

Besides this. really great mod. Keep up the good work :)

**Comment by McJty** [comment]
Mekanism is known to have compatibility issues with other mods. This is not the first time people have reported issues like these

**Comment by Dustmuz** [comment]
okay.. Thats actually nice to know :D 

once again.. 
Keep up the good work :)
