### ISSUE TITLE
Valve not working.

### ISSUE THREAD

**Issue by zevric** [McJty/DeepResonance#196]
I'm playing the FTB Beyond modpack with Deep Resonance version 1.4.6. I have my valve set up correctly to the best of my knowledge but it doesn't transfer the rcl into the tank below even though it's criteria is being met. In the criteria section for it's ui for some reason in the purity slot, unless set to 100 it refuses to have more that 2 digits. So if I set it to 084 it would change it to just 84 after leaving the ui, but the strength and efficiency stay as 3 digit numbers. Not sure if that could be a cause of anything. Also the quality won't go past 99.8% nor will it purify past 84.9%. I don't have the slightest clue what is going on.

**Comment by McJty** [comment]
Show some screenshots of the setup you have (UI and in game)

**Comment by zevric** [comment]
Let me know if you need any other screenshots besides these.
![2017-05-02_08 45 56](https://cloud.githubusercontent.com/assets/22062411/25620408/ebcc9fb8-2f13-11e7-9513-9cd7ea62fa68.png)
![2017-05-02_08 46 08](https://cloud.githubusercontent.com/assets/22062411/25620410/ebeceb1a-2f13-11e7-8e4e-39daac9cf45d.png)
![2017-05-02_08 46 14](https://cloud.githubusercontent.com/assets/22062411/25620409/ebd467b6-2f13-11e7-873e-fb4e99600e97.png)

**Comment by McJty** [comment]
Why use 005? Just use 5

**Comment by zevric** [comment]
It keeps setting it to 005 on it's own, that's why i mentioned the 84 bit.

**Comment by zevric** [comment]
Ok, so i just changed it to 5 on both and it stayed and now it seems to be working...I'm so lost lol

**Comment by McJty** [comment]
Not sure what was going on before

**Comment by zevric** [comment]
Neither do I but thanks for your help still lol. I appreciate you, you fine gentleman you.
