### ISSUE TITLE
[1.10.2] Dependent on newer version of compatlayer than what is available.

### ISSUE THREAD

**Issue by Compegen** [McJty/DeepResonance#197]
Version `1.1x-1.4.7` requies compatlayer version 0.2.**6** while only version 0.2.**5** is available.
_________
![cl](https://cloud.githubusercontent.com/assets/8009507/25631529/4fe003a6-2f36-11e7-8c2d-ca42f574eaf5.PNG)

**Comment by McJty** [comment]
Hold on. Releasing compatlayer in a moment

**Comment by McJty** [comment]
Released
