### ISSUE TITLE
[1.10.2][v1.4.7] Dedicated Server - Exception Ticking World Entities Crash

### ISSUE THREAD

**Issue by Alaberti** [McJty/DeepResonance#199]
Crash Report: https://pastebin.com/raw/9sLa3CBU

I have a Deep Resonance tank set to export water to a Thermal Expansion steam dynamo using Chickenbones Fluid Translocators. Upon exiting the server, I got this crash report on the server side, presumably because the chunk was not loaded.

**Comment by McJty** [comment]
We will check this out

**Comment by TwitchtvCarbs** [comment]
This also occures in the 1.11.2 versions aswell, Anytime a the chunk is unloaded.

https://github.com/TwitchtvCarbs/The-Collection-Issues/issues/29
