### ISSUE TITLE
Tanks cause crash after chunk unloads and reloads

### ISSUE THREAD

**Issue by GreatOrator** [McJty/DeepResonance#200]
Had this issue reported at my github:

https://github.com/GreatOrator/TolkienCraft-3-Map/issues/15

Apparently after letting the chunk unload when trying to re-enter the chunk (reload) the only way to stop the crash is to mcedit the map and delete the tank

**Comment by McJty** [comment]
That should be fixed in the version I released five minutes ago (1.4.8). What version are you using?

**Comment by GreatOrator** [comment]
the version prior to 5 minutes ago :P

I will update tonight and let you know.  Thank you!

**Comment by GreatOrator** [comment]
Had someone test, this does fix the issue, thanks!
