### ISSUE TITLE
Get Exception ticking world entities when updating a beyond server.

### ISSUE THREAD

**Issue by exultanthabit** [McJty/DeepResonance#202]
Minecraft Version: 1.10.2
Pack: Beyond 1.5.3 -> 1.6.1
Deep Resonance Version: deepresonance-1.1x-1.4.7
Plugins: None
Crash Log:
https://pastebin.com/j27sf8ai
Description: 
I get this crash every time I try to update my server to Beyond's recommended version (now 1.6.1 .) Potentially a new compatibility issue.

**Comment by McJty** [comment]
Already fixed in latest deep resonance
