### ISSUE TITLE
DR Tanks crash the server when chunk unloads.

### ISSUE THREAD

**Issue by ShakinBabyBacon** [McJty/DeepResonance#204]
[crash-2017-05-16_07.30.19-server.txt](https://github.com/McJty/DeepResonance/files/1006160/crash-2017-05-16_07.30.19-server.txt)

As you can see the Deep Resonance Tanks crash the server when the chunk they are in unloads. removing the tanks has stopped the crashes.

this is on FTB Beyond running the newest versions of Sponge, Forge and the FTB Modpack

**Comment by McJty** [comment]
Fixed in latest version of Deep Resonance
