### ISSUE TITLE
[1.10.2] Server Crash

### ISSUE THREAD

**Issue by Camrais** [McJty/DeepResonance#206]
Hi,

i placed down a DR smelter with two tanks and a purifier with a tank. Afterwards i went to my armoma mining world and had a crash, my server where im running it on crashed. 

> Description: Exception ticking world entities
>
>java.lang.NullPointerException: Exception ticking world entities
>	at java.util.Objects.requireNonNull(Objects.java:203)
>	at java.util.Optional.<init>(Optional.java:96)
>	at java.util.Optional.of(Optional.java:108)
>	at mcjty.deepresonance.blocks.tank.TileTank.onTileUnloaded(TileTank.java:170)
>	at mcjty.deepresonance.blocks.tank.TileTank.onChunkUnload(TileTank.java:158)
>	at net.minecraft.world.World.func_72939_s(World.java:1843)
>	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
>	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
>	at java.lang.Thread.run(Thread.java:745)

Full crash log:

[crash-2017-05-18_12.24.55-server.txt](https://github.com/McJty/DeepResonance/files/1010591/crash-2017-05-18_12.24.55-server.txt)

Client didn't crash only Server. 

Using version:

deepresonance-1.1.x-1.4.7
mcjtylib-1.1.x-2.3.11

Hope the log gives enough informations.

Greetz,
Camrais

**Comment by McJty** [comment]
When will people stop reporting bugs for a version that is outdated...

**Comment by McJty** [comment]
Sorry for being annoyed but this is already almost the tenth ticket of this sort even though the fixed version has been out there for some time already

**Comment by Camrais** [comment]
Well i wrote it when i saw that the post from december is still open... Sry for bothering.
