### ISSUE TITLE
Deep Resonance 0.5.0 server crash...

### ISSUE THREAD

**Issue by therealericbj** [McJty/DeepResonance#21]
Sorry I broke it somehow...

We got this when placing the Generator Controller Block...

http://pastebin.com/P9r4Gv0p

Restarted server, block was placed before the crash, so we tried to place a lever next to it, to generator on.  We got the same error.

We tried to destroy the block while in creative mode, same error.

So we tried to build a box around it.  It crashed the client and not the server, when any block touched the air blocks that surround the Generator Controller Block.

The Client said "Internal Server Error" and the server console said this...

http://pastebin.com/3KeYA2f3

Forge 1492
deepresonance-0.5.0.jar

I hope this is sort of helpful.

Let me know if I can get more information for you.

Happy Hunting...

**Comment by McJty** [comment]
I will check this out. Thanks for reporting

**Comment by McJty** [comment]
I don't understand this crash. It contains ProjectRed as well as Microblocks code in the stacktraces. I'm confused...

**Comment by therealericbj** [comment]
Yea, I've made something new and unique...

Is there anymore details I can get you to make this less confusing?

**Comment by McJty** [comment]
Well I still think it is confusing the way this error gets reported but I think I have fixed it. I will do some more testing later today and when I release 1.0.0 it should be ok hopefully.
