### ISSUE TITLE
Some machines not craftable and no image displayed in manual

### ISSUE THREAD

**Issue by ExDomino** [McJty/DeepResonance#215]
Hello,

There is two bugs in 1.12 :
1) Some machines and items from the mod are not craftable. No recipes are show in JEI for them
2) In the manual (that is not craftable either) the images are not displayed.

DeepResonance 1.4.8 beta1;
ElecCore 1.8.428;
mcjtylib 2.4.2;
Forge 14.21.1.2397.

**Comment by ExDomino** [comment]
Your mod is not the only one that had uncraftable recipes. RF Tools and Immersive Engineering are affected as well. I think the issues conern shapeless recipes only.

**Comment by McJty** [comment]
Can you be more specific? What items are not craftable for you?

**Comment by ExDomino** [comment]
Hello, there is the list of no craftable blocks and items from your mod:

First of all, the Deep Resonance Manual itself;
The Filter Material;
The Liquid Injector;
The Generator;
The Generator Controller;
The Energy Collector;
The Crystalizer;
The Pedestal;
The Lens;
The Infusing Laser;
The Dense Glass;
The Dense Obsidian;
The Poisoned Dirt (this is maybe intented as it's a poison effect that transforms dirt and grass);
The Resonating Machine Frame;
The Radiation Suit, all pieces (maybe intented as well as it's noticed WIP).

That's it. Some other blocks and items are craftable, like the Radiation Monitor and the Smelter, where the recipe is there for the Smelter but cannot be crafted because of the Resonating Machine Frame that cannot be crafted itself. Item about the Purifier that lacks the Filter Material as well and the Valve for the same reason.

**Comment by McJty** [comment]
I will fix this soon

**Comment by McJty** [comment]
Fixed next release

**Comment by ExDomino** [comment]
Is the problem about Forge that was changed how crafting recipes work?
Because a lot of mods are affected, not just yours. I'm curious.

**Comment by McJty** [comment]
No it is just that if there is even a tiny error in one of the recipes forge simply stops scanning further recipes so a lot were missing due to a very tiny error :-)

**Comment by ExDomino** [comment]
Will the new release become available today?

**Comment by McJty** [comment]
It is already uploaded. Just waiting for CurseForge to approve it

**Comment by ExDomino** [comment]
And does CurseForge take a lot of time to approve? xD
I'm curious because I created my modpack on Tekkit and when I want to update it, it takes a lot of time to make that clients recognize the update. But for Tekkit I think it's an automatic script that is just too long.

**Comment by McJty** [comment]
It is pretty much unpredictable. Can be between a minute and longer. Never had it take longer then a day though
