### ISSUE TITLE
Generator issue

### ISSUE THREAD

**Issue by NicosaurusRex99** [McJty/DeepResonance#217]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.106.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 7/14/17 7:37 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: mcjty.deepresonance.blocks.generator.GeneratorTileEntity.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I
	at mcjty.deepresonance.blocks.generator.GeneratorTileEntity.checkStateServer(GeneratorTileEntity.java:248)
	at mcjty.deepresonance.blocks.generator.GeneratorTileEntity.func_73660_a(GeneratorTileEntity.java:243)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.deepresonance.blocks.generator.GeneratorTileEntity.checkStateServer(GeneratorTileEntity.java:248)
	at mcjty.deepresonance.blocks.generator.GeneratorTileEntity.func_73660_a(GeneratorTileEntity.java:243)

-- Block entity being ticked --
Details:
	Name: minecraft:deepresonance_generator // mcjty.deepresonance.blocks.generator.GeneratorTileEntity
	Block type: ID #508 (tile.deepresonance.generator // mcjty.deepresonance.blocks.generator.GeneratorBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (202,72,70), Chunk: (at 10,4,6 in 12,4; contains blocks 192,0,64 to 207,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #508 (tile.deepresonance.generator // mcjty.deepresonance.blocks.generator.GeneratorBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: McJty
	All players: 1 total; [EntityPlayerMP['NicosaurusRex99'/2663, l='McJty', x=199.94, y=72.00, z=70.59]]
	Chunk stats: ServerChunkCache: 510 Drop: 0
	Level seed: 7739906562676119803
	Level generator: ID 06 - lostcities, ver 0. Features enabled: true
	Level generator options: { "profile": "chisel" }
	Level spawn location: World: (116,64,252), Chunk: (at 4,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8673 game time, 8673 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64221 (now: false), thunder time: 157411 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2062125232 bytes (1966 MB) / 2699558912 bytes (2574 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2412 Optifine OptiFine_1.12_HD_U_C4 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2412.jar) 
	UCHIJAAAA	forge{14.21.1.2412} [Minecraft Forge] (forge-1.12-14.21.1.2412.jar) 
	UCHIJAAAA	immcraft{1.3.5} [Immersive Craft] (immcraft-1.12-1.3.5.jar) 
	UCHIJAAAA	aquamunda{0.1.1beta} [Aqua Munda] (aquamunda-1.12-0.1.1beta.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.13} [Chisel] (Chisel-MC1.12-0.0.13.13.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UCHIJAAAA	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.12-1.4.8.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.3-1.12-law.jar) 
	UCHIJAAAA	intwheel{1.2.7} [Interaction Wheel] (intwheel-1.12-1.2.7.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.106.6841692} [Inventory Tweaks] (InventoryTweaks-1.63+beta.106.jar) 
	UCHIJAAAA	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	jeresources{0.8.1.14} [Just Enough Resources] (JustEnoughResources-1.12-0.8.1.14.jar) 
	UCHIJAAAA	lostcities{0.0.17beta} [The Lost Cities] (lostcities-1.12-0.0.17beta.jar) 
	UCHIJAAAA	lostsouls{0.0.2beta} [Lost Souls] (lostsouls-1.12-0.0.2beta.jar) 
	UCHIJAAAA	nice{0.1.0} [Nice] (nice-1.12-0.1.0.jar) 
	UCHIJAAAA	rftools{6.10} [RFTools] (rftools-1.12-6.10beta4.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UCHIJAAAA	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02.jar) 
	UCHIJAAAA	theoneprobe{1.4.13} [The One Probe] (theoneprobe-1.12-1.4.13.jar) 
	UCHIJAAAA	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.106.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['NicosaurusRex99'/2663, l='McJty', x=199.94, y=72.00, z=70.59]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0 - Build 8.15.10.2712
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by McJty** [comment]
Fixed next release
