### ISSUE TITLE
[1.12.1] Invalid Ore Dictionary Registration

### ISSUE THREAD

**Issue by Preminenc3** [McJty/DeepResonance#224]
[Log Code](https://pastebin.com/KxhvUVBY)

**Comment by ProsperCraft** [comment]
Is this related to this magic bees crash?

https://github.com/Lach01298/MoreBees/issues/59

**Comment by bookerthegeek** [comment]
Duplicate of https://github.com/McJty/DeepResonance/issues/220

**Comment by McJty** [comment]
Fixed next release
