### ISSUE TITLE
OpenComputers dependency is not all lowercase

### ISSUE THREAD

**Issue by mezz** [McJty/DeepResonance#228]
https://github.com/McJty/DeepResonance/blob/6f5af2d071d443c89797b453d41a97ca105d3390/src/main/java/mcjty/deepresonance/DeepResonance.java#L45

The ModId for OpenComputers is "opencomputers" so the dependency info will not work as intended.
https://github.com/MightyPirates/OpenComputers/blob/a4b86524791d05d89e74bc38b030dacda321ab5c/src/main/scala/li/cil/oc/OpenComputers.scala#L19

**Comment by McJty** [comment]
Fixed next version
