### ISSUE TITLE
Server Crash when placing Tank with Fastcraft installed.

### ISSUE THREAD

**Issue by GustoniaEagle** [McJty/DeepResonance#23]
http://pastebin.com/xP6sHreF

**Comment by McJty** [comment]
This bug has already been reported and has nothing to do with fastcraft. We will fix this for next release (tomorrow).

**Comment by GustoniaEagle** [comment]
Awesome, thanks.

**Comment by Elec332** [comment]
Today? Aha, means that I got some work to do  :P

**Comment by McJty** [comment]
It would be great if you could. This is a bit of a show-stopper (together with the lighting update thing which is a show stopper on servers)
