### ISSUE TITLE
[Client Crash] 1.12.2 Deep Resonance with ElecCore

### ISSUE THREAD

**Issue by tjsd** [McJty/DeepResonance#232]
I am currently building a custom mod pack for 1.12.2, adding in deep resonance crashes the client and refers to elec232.core. Removing elecore and deep resonance resolves the client crash.

forge 2512
deepresonance            | 1.4.9           | deepresonance-1.12-1.4.9.jar
eleccore                 | 1.7.431         | ElecCore-1.11-1.7.431.jar

Crash Log > https://pastebin.com/KMFtnF3k

**Comment by McJty** [comment]
Use ElecCore for 1.12. You are using the version for 1.11 (ElecCore-1.11-1.7.431.jar)
