### ISSUE TITLE
[1.12] Resonating Ore does not smelt in Thermal Expansion's Redstone Furnace

### ISSUE THREAD

**Issue by DarkMorford** [McJty/DeepResonance#233]
The Redstone Furnace block from Thermal Expansion will not smelt Resonating Ore, though it did in versions prior to 1.12.

Looking over the commit history, it looks like the smelting recipe registration was moved to `postInit` at the same time the crafting-table recipes were transitioned to JSON. I suspect that this causes the smelting recipe to be registered after the Redstone Furnace scans the registry and adds all of the smelting recipes it finds to its own list.

I believe that registering the smelting recipe earlier (in `init` or even `preInit`) should fix this issue.

**Comment by McJty** [comment]
I will check this out soon

**Comment by McJty** [comment]
Fixed next release
