### ISSUE TITLE
tank crashes dire20 1.12.2 server

### ISSUE THREAD

**Issue by unstablecraft** [McJty/DeepResonance#236]
DeepResonance tank  http://prntscr.com/hb79ps <screenshot of tank>
forge: 2531
spongeforge: 1.12.2-2529-7.0.0-BETA-2732
server pack: direwolf20 1.12.2

**Comment by McJty** [comment]
I need a crashlog and also what you're doing to cause this crash. More details please!

**Comment by unstablecraft** [comment]
https://pastebin.com/v832Tkg8
 just placing the tank into the world

**Comment by NightbringerMc** [comment]
We got the same issue on our servers

**Comment by McJty** [comment]
Apparently the modpack was built with the wrong version of ElecCore. Can you try updating ElecCore to the current latest to see if that fixes it?

**Comment by unstablecraft** [comment]
sure server isnt online yet

**Comment by unstablecraft** [comment]
a link would be handy curse is acting up again

**Comment by McJty** [comment]
The latest you can get from:
https://minecraft.curseforge.com/projects/eleccore-rendering-library/files

**Comment by NightbringerMc** [comment]
Doesnt crash on clients

**Comment by unstablecraft** [comment]
updated my client and server now
we will know in a sec

**Comment by unstablecraft** [comment]
@McJty http://prntscr.com/hb7t3x
aaand its fixed

**Comment by McJty** [comment]
Thanks! So it is a pack error and I can close this :-) 
Thanks for testing

**Comment by unstablecraft** [comment]
no problem
