### ISSUE TITLE
DR Tanks make more sense to use as pipes than as tanks

### ISSUE THREAD

**Issue by moonheart08** [McJty/DeepResonance#239]
Seriously. I personally use them in all my large powergen setups because they have a instant, unlimited transfer rate between themselves, and no cap as far as the eye can see.
Its better to make a bunch of cheap tanks than to make pipes from other mods, because of the properties they have.

And, on the other hand, tanks from other mods are almost always better at storing things than DR Tanks,

**Comment by McJty** [comment]
I'll made the recipe somewhat harder to avoid this
