### ISSUE TITLE
Caught exception from Deep Resonance 1.5.0

### ISSUE THREAD

**Issue by border999** [McJty/DeepResonance#242]
https://pastebin.com/ugLfSBFk
Something about the resonating block is messing up.

**Comment by McJty** [comment]
Seems something is corrupt on your side because those classes are certainly part of the mod and the mod is working in 1.12 (it is included in the latest FTB pack for 1.12 for example)

**Comment by border999** [comment]
Optifine?

**Comment by McJty** [comment]
Would be strange. I'm thinking more about corrupt zips or something

**Comment by border999** [comment]
Question: If it turns out to be another mod messing with your mod? Would you patch it an exception for that mod or. or would the other guy?

**Comment by border999** [comment]
Issue resolved. Turns out the "Latest download that curseforge gave me of mcjtylib was for 1.11.2. Went back and manually downloaded 1.12.2. All clear.
