### ISSUE TITLE
Crash on Deep Resonance 1.5.0

### ISSUE THREAD

**Issue by Divineaspect** [McJty/DeepResonance#243]
https://pastebin.com/vDAZTYKe

Looks like the same crash as https://github.com/McJty/DeepResonance/issues/242
But I have the 1.12 version

**Comment by McJty** [comment]
Very strange.. Do you have Open Computers? If so which version?

**Comment by Divineaspect** [comment]
Nope, no Open Computers

**Comment by McJty** [comment]
@josephcsible Just a long shot but could there be a problem in case OC is not there? There are several complaints, both in 1.10 as in 1.12 with this but I have no clue what is happening

**Comment by josephcsible** [comment]
@McJty It doesn't look like it. I don't see any way it could be related, though I suppose it couldn't hurt to try adding it.

@Divineaspect What version of McJtyLib are you using? (The full file name)

**Comment by josephcsible** [comment]
Side note: it may be worth giving McJtyLib a class with @Mod, even though it's not actually a mod, just so its exact version will show up in these sorts of crash logs.

**Comment by Divineaspect** [comment]
1.1x-2.5.1 which in in it's mod info says it's for 1.11

**Comment by josephcsible** [comment]
Okay, that's the exact same problem as in #242. 1.1x is 1.10/1.11 only. Replace it with the 1.12 one and it will work fine.

**Comment by Divineaspect** [comment]
It amazes me that I read #242 and still managed to not apply it correctly.

**Comment by Divineaspect** [comment]
Thank you all
