### ISSUE TITLE
NoSuchFieldError on Server Start

### ISSUE THREAD

**Issue by Ommina** [McJty/DeepResonance#26]
http://pastebin.com/D3upBaMJ

ElecCore{1.4.175} [ElecCore] (ElecCore-1.7.10-1.4.175.jar) 
McJtyLib (1.7.0) from mcjtylib-1.7.0.jar
deepresonance{1.1.0beta1} [DeepResonance] (deepresonance-1.1.0beta1.jar)

Not much to add to it other than that.  Starts fine on client.  Pouts on the server.  Pretty sure I've the most recent builds of everything.

**Comment by McJty** [comment]
Build 208 should hopefully fix this
