### ISSUE TITLE
Divide by 0 error.

### ISSUE THREAD

**Issue by Jkosio23** [McJty/DeepResonance#286]
https://paste.ee/p/Ty4C4 modpack: ATM 7 v 0.2.44. forge 39.0.85 deep resonance's file also seems to be mislabeled as 1.16 3.0.1-beta

**Comment by Jkosio23** [comment]
I was mining up an energy collector and a generator block which didn't have a controller connected to it

**Comment by McJty** [comment]
I cannot reproduce this problem at all but I'll try to add protection so that it cannot happen anymore. What about mislabed Deep Resonance? It seems ok to me?

**Comment by McJty** [comment]
I fixed the divide by zero
