### ISSUE TITLE
[1.16.5] Server crash (NoClassDefFoundError)

### ISSUE THREAD

**Issue by aking4125** [McJty/DeepResonance#292]
Hello,

Upon attempting to create a server. The server crashes with the following crash report: [crash-2022-04-27_08.52.21-fml.txt](https://github.com/McJtyMods/DeepResonance/files/8572241/crash-2022-04-27_08.52.21-fml.txt)

Removing this mod and the server starts normally. Client works perfectly. Any ideas?

**Comment by McJty** [comment]
Fixed next version (soon)
