### ISSUE TITLE
Cannot see attributes for Liquid Crystal in Deep Resonance

### ISSUE THREAD

**Issue by jjjworley** [McJty/DeepResonance#293]
Cannot see attributes for strength, purity and efficiency when looking at tank containing liquid crystal, so cannot refine to proper levels.

TNP 5 modpack, 1.18.2

**Comment by jjjworley** [comment]
Could a setting possibly be turned off so I can't see the mixture in JEI? I have used this mod for years and I've never had this problem. Now I am stuck using substandard crystals.

**Comment by McJty** [comment]
Do you have TOP?

**Comment by jjjworley** [comment]
Unfortunatly The One Probe is not installed in this pack. I've asked Gberqz the author if he will incorporate it. Thank you for your reply.

**Comment by McJty** [comment]
I'll try to think of an alternative way to see these stats if TOP isn't present

**Comment by McJty** [comment]
In the next version of DR you will be able to right click on the tank with any non-bucket and it will show you the liquid information in the chat

**Comment by McJty** [comment]
Fixed in latest version

**Comment by jjjworley** [comment]
Thank you so much! I've always known you for coming through :)
