### ISSUE TITLE
[1.18.2] Dimensional shards in Laser not working

### ISSUE THREAD

**Issue by YOYOK9** [McJty/DeepResonance#295]
Dimensional shards do not show as usable in the 1.18.2 version of Deep Resonance. 
proof: https://puu.sh/J3qnT/cdb9809d74.png

I tested all the other components in my inventory and they match the the file I got the ingredients from (InfusionBonusRegistry.java) just not the shards. 

Also tested in a pack with just the mods needed and jei, same result. 

Versions: 
mc: 1.18.2
Forge: 40.1.25
DeepResonance: 3.0.5
RFToolsBase: 1.18-3.0.7

**Comment by McJty** [comment]
Will be fixed next release. Thanks for reporting
