### ISSUE TITLE
Fluid Voiding Bug

### ISSUE THREAD

**Issue by Direwolf20-MC** [McJty/DeepResonance#298]
If you place a tank above and below a Purifier - and then remove the tank below - the fluid in the tank above keeps going into the purifier and then gets voided. 

The same seems to happen with a tank -> Valve -> Tank setup. I had:

1000mb in tank above
Valve set to 6000mb
6000 mb in tank below

When I broke the tank below the valve, the fluid in the tank above the valve disappeared.

**Comment by McJty** [comment]
Oops I'll check it out


Op vr 10 jun. 2022 17:40 schreef Direwolf20-MC ***@***.***>:

**Comment by McJty** [comment]
Should be fixed now
