### ISSUE TITLE
Cristallizer => Crashing game 1.16.5

### ISSUE THREAD

**Issue by Guslloween** [McJty/DeepResonance#300]
For some reason, the crystallizer was not forming the crystals, when I removed it and put it back, the game crashed and when I broke the tank below it and placed it again, the game crashed again, to the point that even entering the world, the game closes immediately. I removed optifine and the problem continues, when the prerequisites to pass the second valve are met and finally transfer the liquid crystal resonance, the game crashes in the same part, the crystallizer.

The current fluid corresponds to:
Quality: 96.4%
Purity: 82%
Strength: 96%
Efficiency: 96%

I'm attaching the log with(out) optifine.
[crash-2022-06-11_13.34.19-client.txt](https://github.com/McJtyMods/DeepResonance/files/8884390/crash-2022-06-11_13.34.19-client.txt)
[crash-2022-06-11_23.34.42-client.txt](https://github.com/McJtyMods/DeepResonance/files/8885107/crash-2022-06-11_23.34.42-client.txt)
.
PS: deepresonance-1.16-2.0.7

**Comment by McJty** [comment]
I will implement a fix for this in Deep Resonance but you can also fix this by upgrading Java. Your Java 8 version is REALLY old. Keep it Java 8 though. Just a more recent version

**Comment by McJty** [comment]
Should be fixed now

**Comment by Guslloween** [comment]
Thanks, its works now and about the java; I discovered that java updated but didn't removed the old version.
