### ISSUE TITLE
[3.0.6] Tank description shows wrong amount of buckets it can hold

### ISSUE THREAD

**Issue by MyPod1** [McJty/DeepResonance#301]
The tank shows that it can hold up to 16 buckets, but in reality it can only hold up to 10. If someone thinks that the tank can hold 16 buckets, then the 40-60% (6.400-9.600 mb) lava would be too much and destroy the liquid crystal.

The description of the tank
![Screenshot_1](https://user-images.githubusercontent.com/107436364/173437263-de3114a8-6ba2-49f1-9689-e9ccb4765440.png)

10 buckets of water show that the tank is full
![Screenshot_2](https://user-images.githubusercontent.com/107436364/173437268-dc7ddb37-dee0-402d-ac62-503dbfec06d7.png)

**Comment by McJty** [comment]
Was fixed a while ago
