### ISSUE TITLE
Infusing is much harder (20x more ineffective) than before 1.16 rewrite

### ISSUE THREAD

**Issue by richie3366** [McJty/DeepResonance#302]
It looks like that we went from:
_One infusion consumes 25mb of crystal liquid, to infuse 500mb of RCL_
to:
_One infusion takes 25mb of crystal liquid to infuse only 25mb of RCL_

It affects the following mecanics:
- Infusion is 20 times slower/ineffective (also in terms of percentage increases)
- Infusion costs 20 times more crystal liquid, time and energy if we scale them to the same amount of RCL to be infused

Proofs:
Stated clearly there in MC 1.12 version:
https://github.com/McJtyMods/DeepResonance/blob/1.12/src/main/java/mcjty/deepresonance/config/ConfigMachines.java#L170-L176

Implicitely stated there in 1.15:
https://github.com/McJtyMods/DeepResonance/blob/1.15/src/main/java/mcjty/deepresonance/api/infusion/InfusionBonus.java#L21

New config (1.16 & 1.18) has now only one variable:
https://github.com/McJtyMods/DeepResonance/blob/1.16/src/main/java/mcjty/deepresonance/modules/machines/util/config/LaserConfig.java#L35-L36
Used on two different cases (first & last selected lines):
https://github.com/McJtyMods/DeepResonance/blob/1.16/src/main/java/mcjty/deepresonance/modules/machines/block/LaserTileEntity.java#L233-L244

**Affects 1.16 & 1.18.2 versions**

**Comment by McJty** [comment]
Well spotted. I'm fixing this right now

**Comment by McJty** [comment]
Fixed!
