### ISSUE TITLE
Breaking Empty Tanks results in prior tank stats

### ISSUE THREAD

**Issue by russfort** [McJty/DeepResonance#303]
Direwolf20 1.18 pack
Deep Resonance version 3.0.6

Draining a tank of liquid and breaking it (picking it up), duplicates the original tank.

For example, 
Place a tank above a Purifier with following stats :
6000 mb
Quality 100%
Efficiency 10%
Purity 35%
Strength 10%

Purify liquid to lower tank, purity increases to 60%.
Top tank is empty.

Break top empty tank and receive a tank in inventory with the original volume and stats I started with.

**Comment by McJty** [comment]
Update. This is fixed
