### ISSUE TITLE
1.18 DeepResonance Tank Dupes Lava

### ISSUE THREAD

**Issue by toastonrye** [McJty/DeepResonance#304]
direwolf20 1.18 modpack
deepresonance-3.0.9

When I pipe lava out of the tank, it shows the tank draining and eventually empty. After I break the tank, and place it down again it is full.

I made a 50s, unlisted video demonstrating the behaviour:
https://www.youtube.com/watch?v=fCzxRfXiuWE

**Comment by Tofini** [comment]
works on liquid crystal too

**Comment by JustJinxed** [comment]
Came here to report the liquid crystal dupe. Seems I only needed to make one tank of 100/100/100/100 and it can make as many crystals as I like, so long as I break the tank and replace it afterwards. (as an aside the visual of the tank appears empty when placed until a block update happens)

**Comment by McJty** [comment]
Both the dupe bug and the lack of visual update when placed back are fixed in the latest release
