### ISSUE TITLE
Missing Opcodes for programmer

### ISSUE THREAD

**Issue by aronjanosch** [McJty/DeepResonance#307]
Hello there,

I'm playing DW20 1.18 and i cant find the Opcodes for analyzing DeepResonance Liquids. 

Versions:
* DeepResonance 3.0.1.0
* RFToolsControl 1.8-5.0.6

**Comment by McJty** [comment]
Not ported yet. I'll try to do that soon

**Comment by McJty** [comment]
Busy with this right now. Sorry for the delay

**Comment by McJty** [comment]
Fixed
