### ISSUE TITLE
Tanks are broken in version 3.0.12

### ISSUE THREAD

**Issue by ozhound** [McJty/DeepResonance#312]
All interaction with tanks has broken in this version

here is a link to the issue in the ATM7 1.18.2 pack

https://github.com/AllTheMods/ATM-7/issues/1529

**Comment by McJty** [comment]
Can you be more specific? As far as I can see they are working fine

**Comment by ozhound** [comment]
HI Mate,

I don't know what else to tell you, nothing works with the tanks, you cant pipe stuff in or out via buckets, piping systems, valves no longer push/pull nor does the smelter melt the resonating ore and push it up into the top tank. (with another tank with 5 buckets of lava in it below) 3 other people confirm this is the case at that other issue.

if it works fine then maybe its a conflict with another mod or setting in ATM7

**Comment by McJty** [comment]
Weird. I'll check it out. About the buckets that's normal. The deep resonance liquid can't be put in buckets

**Comment by ozhound** [comment]
Yeh I was more referring to putting lava into a DR tank

**Comment by McJty** [comment]
Can you show me a screenshot of a bit working setup with the smelter?

**Comment by ozhound** [comment]
well i cant show the original setup as i broke it down during my troubleshooting process. but it was working prior to upgrading atm7 pack from .30 to .31 which updated Deep Resonance to 3.0.12.

to give you an idea, i always setup my DR systems the same as you have in the initial screen shot on the wiki here https://github.com/McJtyMods/DeepResonance/wiki/Tutorial
![2022-09-25_18 44 52](https://user-images.githubusercontent.com/3649237/192139605-917cfd12-bd58-4d01-809c-aad3aa1e49a3.png)

**Comment by McJty** [comment]
I found the bug. Fixing now

**Comment by McJty** [comment]
Fixed in the upcoming release

**Comment by ozhound** [comment]
awesome! thanks
