### ISSUE TITLE
[1.19.2] Crash on server start

### ISSUE THREAD

**Issue by waddon1** [McJty/DeepResonance#313]
Just updated some mods and now Deep Resonance is causing my server to crash
[crash-2022-10-01_22.36.02-fml.txt](https://github.com/McJtyMods/DeepResonance/files/9691306/crash-2022-10-01_22.36.02-fml.txt)

**Comment by waddon1** [comment]
Client also crashes on startup

**Comment by McJty** [comment]
Fixed
