### ISSUE TITLE
Empty Tank resets to last amount when broken (duped liquids!)

### ISSUE THREAD

**Issue by DerHope** [McJty/DeepResonance#314]
Hi there!
First, thanks for this great mod to tinker around with! 
I'm no coder here, so hopefully I can provide all you need to pinpoint the issue...
I use the Direwolf20 1.18 modpack, the version of DeepResonnance is 3.0.9. 

When I empty a tank completely and break it, it somehow resets to a fuller state! 
Not sure what the exact state is to which it resets, but it seems that the time it was broken with x buckets in it is retained. 
Which basically gives to whoever is such inclined opportunity to cheat:
Make the perfekt tank. 
Empty it break it. 
Replace it. 
All there! 
Which I don't like. 
Could you please look into this? 

[edit] The kind of liquid doesn't matter, so far I tried (of course) Liquid Crystal and Lava, and Water...

**Comment by McJty** [comment]
Update the mod. That's a very old version

**Comment by DerHope** [comment]
Ok... wow! Thanks for the quick answer!!
Unfortunately, I only use the mod "as is" and do not have any kind of contact to the mod author, Direwolf20 (but may you do?), I don't think I can simply update this in a stable way for the rest of the pack...

**Comment by McJty** [comment]
Make a backup of your world and update all the mods and forge. That's usually the best way

**Comment by DerHope** [comment]
Okaaay, Iwill try that. Since it's my first time tinkering with a modpack on that level, please forgive me for asking one more thing though: 
I'm running a Linux server and me and a friend of mine connect to this with FTB clients. 
I suppose I need to update both server **and** all client's mod files, right?

**Comment by McJty** [comment]
yes indeed

**Comment by DerHope** [comment]
I was afraid you would say that. ^^°
Still, many thanks!!!
