### ISSUE TITLE
Can't insert Lava into tank, in latest version of ATM7

### ISSUE THREAD

**Issue by Linkdeous** [McJty/DeepResonance#315]
Hello, i wanted to say i love the mod, but cannot use it rn, in ATM7 i cannot use the mod because i can't place lava, either by right clicking it with a bucket, or putting pipes (tried in creative with pretty much every way i could think of to move fluids) and didn't managed to put a single drop of lava inside the tank..
Is the mod broken for the latet version ? i rememebr it worked well before :( Really hope you'll see this soon ! goodbye thank you for reading !

**Comment by McJty** [comment]
What version of the mod?

**Comment by Linkdeous** [comment]
seems to be version 3.0.12 in the version 0.4.32 of ATM7

**Comment by McJty** [comment]
Yes, that's old. That bug has been fixed now
