### ISSUE TITLE
Unable to disable world gen

### ISSUE THREAD

**Issue by Tellik** [McJty/DeepResonance#316]
In the config file, there doesn't appear to be a way to disable world gen, specifically for resonant ore in the overworld. It has options for disabling ore in the nether, end, and other.

It still generates if generateOreOther is set to false, and there is no way to set the chancesToSpawn to 0. This results in ore generating regardless.

A dirty way to work around this for me was to set the min/max Y ranges to below the world, such as -100/-99. While it does work, and I haven't seen any generate in the world, it feels like a dirty method for accomplishing this goal.

**Comment by McJty** [comment]
It's the only way

**Comment by Tellik** [comment]
Ah got it. Alright thank you.
