### ISSUE TITLE
[1.19] Flowing texture of liquid crystal fluid returns null

### ISSUE THREAD

**Issue by XFactHD** [McJty/DeepResonance#319]
The `IClientFluidTypeExtensions` implementation of the liquid crystal fluid type (https://github.com/McJtyMods/DeepResonance/blob/1.19/src/main/java/mcjty/deepresonance/modules/core/fluid/FluidLiquidCrystal.java#L23-L38) returns null for the flowing texture. This violates the contract of `IClientFluidTypeExtensions#getFlowingTexture()` which mentions that only the empty fluid may return a null texture location.

Forge: 1.19.2-43.2.3
DeepResonance: 1.19-4.0.8

**Comment by McJty** [comment]
um, now that I'm actually checking this code. Where is it returning null?

**Comment by McJty** [comment]
nm

**Comment by McJty** [comment]
Will be fixed next release
