### ISSUE TITLE
Right-clicking filled Tanks with buckets only returns one filled bucket

### ISSUE THREAD

**Issue by VictiniX888** [McJty/DeepResonance#32]
When there is more than one bucket on hand and I right-click a Tank with, say, lava in it, the stack of buckets will turn into 1 lava bucket. The rest just disappear.

Using latest build on drone.io

You could do it like how other mods do it: don't replace the stack in hand, but instead just take one bucket and return a lava bucket (or anything else) in another inventory slot

**Comment by McJty** [comment]
How do you get a stack of filled buckets btw? Normally that is not possible. So no idea how you can even get this bug to reproduce?

**Comment by McJty** [comment]
Oh stupid me. It is the other way around :-)

**Comment by McJty** [comment]
Fixed in next release
