### ISSUE TITLE
[1.19.2] Crash on world load - java.lang.RuntimeException: Don't access this client-side!

### ISSUE THREAD

**Issue by Peca21** [McJty/DeepResonance#320]
I created my own modpack and pregenerated a world two weeks ago, but I didn't play it. Today I loaded my world and got this crash
Crash Report: https://paste.ee/p/1CvN2
latest.log: https://paste.ee/p/vZJKJ

deepresonance-1.19-4.1.0.jar
mcjtylib-1.19-7.1.1.jar
Forge 43.2.4

**Comment by timm-u** [comment]
Can confirm, exact same crash on world load.
Crash report: https://paste.ee/p/mSMpC
latest.log(includes the crash part only): https://paste.ee/p/8swrk

deepresonance-1.19-4.1.0.jar
mcjtylib-1.19-7.1.2.jar
Forge 43.2.4

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed for next version of 1.18.2, 1.19.2, and 1.19.3
