### ISSUE TITLE
[1.20] Pedestal consumes 2 crystals to place 1; extra is voided.

### ISSUE THREAD

**Issue by Umber0010** [McJty/DeepResonance#322]
When attempting to automate the placement and removal of resonating crystals, having more than 1 Resonating Crystal in the pedestal will result in one crystal being placed on the spot in front of it. But 2 crystals being removed from the internal buffer.

Steps to reproduce:

1. Place a pedestal
2. Place 2 crystals in the internal buffer.

**Comment by McJty** [comment]
I'll check this out soon

**Comment by McJty** [comment]
Fixed next version
