### ISSUE TITLE
Feature Request: Resonating Plate Storage Block

### ISSUE THREAD

**Issue by Divineaspect** [McJty/DeepResonance#34]
I would like to request a storage block of 9 resonating plates.
in addition I'd like it to respond to a redstone signal and/or laser beam by emitting radiation.

**Comment by McJty** [comment]
What are you planning to do with this? :-)

**Comment by Divineaspect** [comment]
1) I like to display my wealth of resources in block form.
2) I like the idea of PVP applications of radiation without risking too many valuable resources.
3) I'm considering making worldgen structures where that's the treasure, to represent an ancient technology, and a danger to be understood and learned from.

**Comment by McJty** [comment]
Done for next release. Note that this will use the random tick system. That means it will not consistently give out radiation when it has a redstone signal. Just at random ticks (similar to the random ticks that happen with crops and such)
