### ISSUE TITLE
Server crash on boot - Mod interaction

### ISSUE THREAD

**Issue by iamomicron** [McJty/DeepResonance#37]
http://pastebin.com/QApixNEX

The issue, I believe is that the Backpacks! mod by brad16840 modifies the biped model. Not sure who's error it technically is.

Also, the client loads fine, it is just the server that does not.

**Comment by McJty** [comment]
It is another problem. I will fix it

**Comment by iamomicron** [comment]
Brilliant!

**Comment by McJty** [comment]
Fixed in next release (busy preparing 1.1.2 now)

**Comment by iamomicron** [comment]
Awesome, thanks for the speedy response!
