### ISSUE TITLE
Purity not exceeding 79.1% (plus other strange behaviour)

### ISSUE THREAD

**Issue by xenoflot** [McJty/DeepResonance#40]
Custom modpack with deepresonance-1.1.2 and mcjtylib-1.8.0

I have replicated the setup pictured in the tutorial. I put in a stack and a bit of ore and currently have 17400 or 17600mb of liquidcrystal circulating around but it's his 79.1% purity and is going no further. The purifier is no longer consuming filter material and there's plenty of space in the output chest.

OK this is weird, the volume in the tank is falling, filters still aren't being consumed, no spent filters being put in the chest, purity is not increasing. Tank below the valve (which is set to 84%) is still showing zero. No progress in the crystalizer, no crystals in the pedestal.

**Comment by McJty** [comment]
Can you show a screenshot of your setup?

You say the amount of liquid in the tank goes down?

**Comment by xenoflot** [comment]
http://i.imgur.com/rTvQhuu.png

The liquid volume slowly increased while I was feeding new ore into the smelter, then was stable at 17600 as expected once I stopped feeding it. I let it run for a while and the purity slowly ticked up as expected. It hit 79.1% and stayed there. I emptied the chests so it would be super-clear if the purifier was doing anything but more than 30 mins later, still nothing higher. 

I broke and replaced a couple of the tanks, being sure to set the flow in the correct direction, then broke and replaced the purifier and the valve. At some point in there, the fluid level started dropping. Now it's a flat zero according to WAILA. It looks empty but there's still an occasional visual flicker of reddy-orange in one of the 5 tanks.

If you like, I can PM you on reddit and auth you to log into the server; it's a custom pack on technic.

**Comment by xenoflot** [comment]
To clarify, as I was writing the original post in this issue, I noticed the liquid level had started dropping. It progressively dropped but 100-200mb every couple of seconds until zero.

**Comment by McJty** [comment]
I will check it out. I'm going to release a new version of DR probably later this week and I'll try to fix this for that version.

**Comment by xenoflot** [comment]
OK! Thanks!

**Comment by McJty** [comment]
BTW, there seems to be a bug but one question. Is your RCL 100% quality? Because if it is less then 100% quality then the maximum purity you can achieve will also be lwess

**Comment by McJty** [comment]
Fixed in next release

**Comment by xenoflot** [comment]
Quality was over 90%, I think around 95-97% I was cooking it a little too quickly at first. Thanks for the rapid service, once again!

**Comment by McJty** [comment]
Ok, if quality is not 100% that explains why you could not get to 85% purity. Later today I will release a new version of DR with the bug fixed that the purifier destroys liquid

**Comment by xenoflot** [comment]
Updated to 1.1.3 and rebuilt the same setup. Siphoned off lower quality juice until I just had the good stuff. Took a long time (10+ mins?) to get from 84.9 to 85% but I now have 22 buckets of 85% pure fluid cycling around in the system.

Sadly the Valve doesn't seem to be passing anything through to the lower tank. I checked that the tank above is in output and the tank below is in input. Valve is set to 85 and 32000.

Incidentally, the "max in tank" defaults to zero. If that's likely to stop purified fluid passing unless set to something higher, you might want to change the default to prevent less-aware operators lodging tickets.

**Comment by McJty** [comment]
Try to set the valve to 84 instead. The values are not precise. Also clear the 32000 to be sure it is not affecting things. A value of 0 in that setting means that it will not check for maximum.

**Comment by xenoflot** [comment]
OK cool, fluid's flowing now and crystals are being generated, thanks.

I suspect that it was a design choice that this system not have one optimal setup, but I suggest that since the label says "Minimum percent purity to transfer", a value of 85 should let 85% fluid.

Thanks again for the rapid reply!
