### ISSUE TITLE
crash from purifier?

### ISSUE THREAD

**Issue by thesixler** [McJty/DeepResonance#43]
I got this crash like immediately after putting down a chest next to a purifier and it crashes when i load up my world. Its a bummer.

[crash-2016-01-23_21.22.05-server.txt](https://github.com/McJty/DeepResonance/files/102181/crash-2016-01-23_21.22.05-server.txt)
[crash-2016-01-23_21.26.35-server.txt](https://github.com/McJty/DeepResonance/files/102182/crash-2016-01-23_21.26.35-server.txt)

**Comment by McJty** [comment]
This bug is fixed in the latest Deep Resonance. If you upgrade it will be ok
