### ISSUE TITLE
Tank Tweaks

### ISSUE THREAD

**Issue by ElKay99** [McJty/DeepResonance#45]
Just some minor things I noticed when using the tanks from Deep Resonance latest build with latest Extra Utilities and Mekanism builds as well

- Tank cannot be picked up on shift-right-click like other Deep Resonance machines (don't know if this is intended)

- Extra Utilities Liquid Transfer Nodes and Transfer Pipes do not connect visibly to tanks (but still transfer RCL with correct attributes yay)
<img width="1440" alt="screen shot 2016-02-20 at 18 41 15" src="https://cloud.githubusercontent.com/assets/12829175/13198597/37f69e32-d805-11e5-8560-9fbf404591e9.png">

-Mekanism Mechanical Pipes transfer RCL but unfortunately it loses its attributes (this might be a problem on Mekanism's side but not sure)
<img width="1440" alt="screen shot 2016-02-20 at 19 00 52" src="https://cloud.githubusercontent.com/assets/12829175/13198602/509c9572-d805-11e5-8224-2a4fcbd98b43.png">

**Comment by Elec332** [comment]
Ill answel you questions/suggestions in the posted order ;)

-This can be added, no problem

-This is an ExU issue (we do not render the pipe), nothing we can about it. 

-This is an issue with mekanism pipes not copying the NBT tags, nothing we can do about that either. Though i'd consider it a bug worth reporting to Mekanism.

**Comment by ElKay99** [comment]
Ok thanks for the info :)

**Comment by Elec332** [comment]
Hmmm, if I take a quick look through the way tank data is saved, it *should* already work...
