### ISSUE TITLE
Pedestal crashes and breaks the world

### ISSUE THREAD

**Issue by RyanP1991** [McJty/DeepResonance#47]
The game crashes and corrupts the world when a pedestal breaks / places a crystal while the generator is running. 

Using version - Deep Resonance - 1.8.9 - 1.1.4-b4

Link to other mods involved - http://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-8-9

Link to the crash report - http://pastebin.com/xdnrPFQT

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
I can reproduce the problem

**Comment by McJty** [comment]
Fixed in latest beta5 release. Your world should load again
