### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by drewbit** [McJty/DeepResonance#48]
Game crashes on launch, here's the log:

http://paste.ee/p/ia1Th

deepresonance-1.8.9-1.1.4beta5
ElecCore-1.8.9-1.4.234
mcjtylib-1.8.9-1.8.1beta7

Edit: Apparently needed latest version of RFtools and RFDim. Might wanna list that as a Dependency on curse.

**Comment by McJty** [comment]
Hmm those should not be needed. I have to check it out. Thanks for finding this

**Comment by McJty** [comment]
Should be fixed in next version hopefully
