### ISSUE TITLE
Crashes with "RadiationModuleItem" class not being found

### ISSUE THREAD

**Issue by DestinyPlayer** [McJty/DeepResonance#50]
http://pastebin.com/tLDeRuTx - Crash Log
http://rghost.net/8947yxNx4 - fml client log.

Everything except for RFTools and Dimensions is the latest version. What might be the problem?

**Comment by McJty** [comment]
That is exactly the problem. You need to update rftools and rftools dimensions. Deep Resonance is trying to use an API of rftools that didn't exist in your version

**Comment by DestinyPlayer** [comment]
Okay, thanks. I thought it was already updated to not require them... Still, thanks a million for answering.
