### ISSUE TITLE
Updated crystal model

### ISSUE THREAD

**Issue by nanakisan** [McJty/DeepResonance#51]
Thought I would waste some time by updating the crystals model. It looked kinda bulky once I saw Dire playing around with it on FC1. So I shrunk it down some from the original, centered it better, fixed an issue where the crystal looked smooshed. Hopefully these images will show the changes I made for you.
![screenshot](https://cloud.githubusercontent.com/assets/2136875/13726766/1aae1ea4-e88b-11e5-80b2-b74521c7fcda.png)
![screenshot1](https://cloud.githubusercontent.com/assets/2136875/13726767/1ada7594-e88b-11e5-8d28-f70f59a7049b.png)
![screenshot2](https://cloud.githubusercontent.com/assets/2136875/13726768/1b8f446a-e88b-11e5-840f-e7f48b6e26a9.png)

If these changes are satisfactory I'll send you the zip file with the updated model.

**Comment by McJty** [comment]
Hmm. I would like to see it in game to make a judgement. Can you either do that or if not just send me the updated blend model?

**Comment by nanakisan** [comment]
Like before the model is a .obj so let me reinstall blender and I'll make the conversion for yah. Give me just a few to get around to it. Gotta head out and do some errands.

**Comment by nanakisan** [comment]
Sorry it took me so long. Guild Wars 2 and some beer really helps you pass the time. xD anyway here is the .blend file for you.
[crystalblock updated.zip](https://github.com/McJty/DeepResonance/files/170893/crystalblock.updated.zip)

**Comment by McJty** [comment]
Hmm, you broke the centering. It should not be in the middle of the crystal. But NM. I'll fix it.

**Comment by nanakisan** [comment]
Hmm thats weird. but I guess thats the benefit with the blender file.

**Comment by McJty** [comment]
I just made a poll on twitter about the old vs the new model. Opinions are mixed and I can't decide either. One remark made me see what exactly the problem is though. The original crystal was very bulky but it looked somehow more natural while the newer crystal is smaller but looks a bit too regular. Not sure if you could do another attempt? Keep the size you have now but made it slightly (not a lot) more irregular?

**Comment by nanakisan** [comment]
easily done my good man. give me a moment

**Comment by nanakisan** [comment]
[crystalblock updated.zip](https://github.com/McJty/DeepResonance/files/171197/crystalblock.updated.zip)

There we go, I changed it's roundness to a more angular shape without compromising the scale.

**Comment by McJty** [comment]
Will check it out tomorrow. Thanks!

**Comment by nanakisan** [comment]
No problem glad I could be of assistance.
