### ISSUE TITLE
Random bugs and MC1.7.10 Support for New  DR Versions

### ISSUE THREAD

**Issue by KinnaT** [McJty/DeepResonance#53]
I noticed that the beta builds all have MC1.8 on them, but I'm playing the [Expedition modpack](http://forum.feed-the-beast.com/threads/1-7-10-expedition-exploration-tech-magic-v1-1-2-updated-18-dec-2015.133217/) and it requires 1.7.10 (I really don't get why...). Are there any compatibility issues if I load it in?  
I looked around because I'm having that issue you reference in the changelog (using 1.1.3)  where my game crashes if I've just removed a machine. My crashes seem to be related to machine + torch placement though. I have my radioactive area well away from everything, on the top of a mountain, so I've safely isolated it to this. The only other thing I can think of is that it started shortly after I redecorated the area with colored glowstone.
The other issue I'm experiencing is that when the machines are almost empty, it graphically freaks out with the RCL. It goes through the final animation for draining liquid, but then flashes back a second later and loops endlessly until I reload the chunk. I mean, I get a red-orange light show, but it ends up with more of a "demon rave" feel than anything.
I wonder if these are an incompatibility with my resourcepack? I'm running with Fanver_Modded.

Unrelated question: Does the ore spawn at any height? I went on an adventure for a few hours and don't know if I'm just really unlucky or if it doesn't spawn at 50+.

**Comment by canitzp** [comment]
It is nearly impossible to create a Mod that is compatible with two completely different MC Versions, so you cannot use  the newer  Version for 1.8 in the Modpack

**Comment by McJty** [comment]
Well there is a 1.1.4 version for 1.7.10 so use at least that version. Reopen if you still have issues with that
