### ISSUE TITLE
Crash with newest Deep Resonance Beta

### ISSUE THREAD

**Issue by sProgg** [McJty/DeepResonance#54]
http://pastebin.com/RFjSYcZb

Not sure what's causing it to be honest.

**Comment by McJty** [comment]
What mods do you have? It seems like there is a mod on your pack that is stil using outdated RF API

**Comment by sProgg** [comment]
Ah that makes since, here's my modlist:
http://puu.sh/nMcdN/6aa134eabf.png

**Comment by canitzp** [comment]
Can you Post the Crash Report please, because inside the Report stands the API Version of all Mods

**Comment by Elec332** [comment]
There is a 1.7.10 mod in that list -_-

**Comment by sProgg** [comment]
Woops yeah I'm dumb. Sorry.
