### ISSUE TITLE
[1.9] Server crash on pedestal crystal placement

### ISSUE THREAD

**Issue by dirtyfargo** [McJty/DeepResonance#56]
Description: Server crashes whenever the pedestal places a resonant crystal. On server reboot, crystal is placed and working fine. :) 
Crash Report: https://gist.github.com/dirtyfargo/f917359552f2b49d1cc3
Forge Version: 12.16.0.1804
Deep Resonance: 1.1.4beta19
Mcjtylib: 1.8.1beta10
ElecCore: 1.4.257

**Comment by McJty** [comment]
I will fix this next release

**Comment by McJty** [comment]
Fixed in upcoming release
