### ISSUE TITLE
Radiaton Suite Crash

### ISSUE THREAD

**Issue by AragurDEV** [McJty/DeepResonance#57]
Server will crash after 1 hour uptime.
Crash-Report: http://pastebin.com/pxTvX9Qy
Version used: 1.8.9-1.1.4beta19

**Comment by aking4125** [comment]
Same issue here sorta. Except it happens immediately when a player joins the server. Close or not.
[crash-2016-03-27_01.10.16-server.txt](https://github.com/McJty/DeepResonance/files/190778/crash-2016-03-27_01.10.16-server.txt)

**Comment by McJty** [comment]
Fixed next release (in a moment)

**Comment by aking4125** [comment]
Awesome! You was quick on that. ;)
