### ISSUE TITLE
Pedestals not connecting to piping.

### ISSUE THREAD

**Issue by Narook** [McJty/DeepResonance#59]
Greetings. I am currently running deepresonance-1.8.9-1.1.4beta23 and have found I can no longer pipe crystals into the pedestals. O have tried Hoppers, piping from BuildCraft, Zoooooom, NeoTech, Ender IO and I even tried Thaumcraft's golems. In the end nothing worked. I know it was working at one point, but I do not know which version that was. Of course I am not sure if you are still supporting 1.8.9 versions, but I figured I'd report it anyway. Thank you for your time.

**Comment by McJty** [comment]
Known bug. Will be fixed next release

**Comment by Elec332** [comment]
I see the code is already there, so im closing this :)

**Comment by kotoroshinoto** [comment]
are there any dev builds or incremental builds with this fix already in place?

**Comment by kotoroshinoto** [comment]
I'm not able to update to 1.9 or 1.94 yet, several mods we're using haven't made the leap.
