### ISSUE TITLE
Backport request. And apparently bug hunters.

### ISSUE THREAD

**Issue by border999** [McJty/DeepResonance#60]
It is highly apparent that the last available version of Deep Resonance for 1.7.10 has quite a few issues with it. I am requesting a single backported version of Deep Resonance for all those players that still use 1.7.10. If you are willing to, please explain your reasoning.

**Comment by McJty** [comment]
What issues are you having exactly?

**Comment by border999** [comment]
Attempting to use the laser to increase the stats of fluid does work. However, it destroys a significant portion of the fluid each time a catalyst is used. This is a serious issue because it makes making decent crystals basically impossible unless I want to spend hours trying to do it. REAL world hours! The catalyst was nether stars to note.

**Comment by border999** [comment]
And I noted from DireWolf20's videos that there was a few issues involving radiation leaking out at odd angles that were still around after you moved to 1.8.9. So those issues would still be there on my 1.7.10 world. All in all not a good situation to have a half baked version of this mod, and that's why I requested the back port.

**Comment by McJty** [comment]
Well the laser destroying the liquid hasn't changed. Be careful when infusing liquids that purity never goes below 0% because that causes the laser to destroy the liquid. This is the same in 1.7.10, 1.8.9 and 1.9 versions.

The leaking radiation may not actually be present in the 1.7.10 version as that was actually a bug that is introduced in the 1.8.9 version (and then fixed). If you know of situations where the radiation does seem to go through the protecting blocks then I'd like to know.

**Comment by border999** [comment]
Allow me to rephrase my statement about fluid destruction. Yes the fluid is increased in its overall stats, but the fluid amount goes down at a rate that was show not to occur in 1.8.9 by DireWolf20 and his server play series. If it destroyed maybe 500mb of fluid during the process I wouldn't be bringing up this request. If I don't pat attention to it. It will simply destroy every bit of the fluid in one fell swoop. I recommend you load up a 1.7.10 world with 1.1.4 running and see what I mean about the fluids being destroyed at an alarming rate and quantity.

**Comment by border999** [comment]
And no, as of yet I have note noted excess radiation leaking at particular angles because I buried my setup in an obsidian box near bedrock level.

**Comment by McJty** [comment]
Are you really sure that the liquid is not destroyed by purity dropping below 0%? Because otherwise I would have no clue what could destroy the liquid. Nothing has changed in that part of Deep Resonance so I have no clue what I would have to backport to fix this.

**Comment by border999** [comment]
I'm positive it's not the purity. And why not just back port the entire mod to 1.7.10,not just a single feature of it's? It would help greatly with my attempts to create a decent Crystal.

**Comment by McJty** [comment]
Well backporting is a HUGE job and not something I would like to do. I can of course fix bugs in the 1.7.10 version so that it is as bug free as the 1.8.9/1.9 versions but then I have to know the bug and be able to reproduce it. Many people (including me) have been using the laser with no problem. Can you desccribe exactly the properties of the liquid you were infusing as well as what you were doing at the time?

**Comment by border999** [comment]
happen to know a good recording software I could use to show you?

**Comment by McJty** [comment]
Hmm I use linux myself and there I use simplescreenrecorder. On windows I have no idea. Sorry

**Comment by border999** [comment]
Quick question, does radiation in high enough doses give you a status effect called instant damage?

**Comment by border999** [comment]
Every time I go near the room I get hit with the status effect 'Instant Damage' and my game freezes permanently. I keep having to reset, and it's making it impossible to even get near my crystal setup.

**Comment by border999** [comment]
Any ideas?

**Comment by McJty** [comment]
No instant damage should not be caused by radiation. Very strange... Can I see your Minecraft log? Perhaps it contains useful information for me

**Comment by mallrat208** [comment]
The only reference to instant damage I saw for Radiation was during the handleDestructionEvent. 
https://github.com/McJty/DeepResonance/blob/1.7.10/src/main/java/mcjty/deepresonance/radiation/RadiationTickEvent.java#L149-L153

```java
        List list = world.selectEntitiesWithinAABB(EntityLivingBase.class, AxisAlignedBB.getBoundingBox(destx - eventradius, desty - eventradius, destz - eventradius, destx + eventradius, desty + eventradius, destz + eventradius), null);
        for (Object o : list) {
            EntityLivingBase entityLivingBase = (EntityLivingBase) o;
            entityLivingBase.addPotionEffect(new PotionEffect(Potion.harm.getId(), 10, damage));
        }
```
It's checking for EntityLivingBase to apply damage, EntityPlayerMP should count for that since it extends EntityPlayer which in turn extends EntityLivingBase.

Barring it being something like that occurring, I'd only imagine it would be some sort of potion id conflict with the other normal effects you'd get

**Comment by McJty** [comment]
If you are having destruction events then it means there must be a HUGE amount of radiation.

**Comment by border999** [comment]
I'm running two very poor crystals.
[latest.zip](https://github.com/McJty/DeepResonance/files/223910/latest.zip)
and there is the last log before I shut down the world.
I think it is of importance to say I was a blaze at the time. Morph mod making that possible.

**Comment by border999** [comment]
also I have Grimoire of Gaia installed, and it has an effect called Instant Damage too.

**Comment by border999** [comment]
Ya... PLEASE get back to me soon, this issue has literally made me unable to get into my world without it being permanently frozen when I get in. I even went so far as to MCEdit the energy extractor machine ting to a different spot, and used NBTExplorer to get rid of the radiation!

**Comment by McJty** [comment]
You can remove all radiation with the command /drgen cleanradiation
Other then that I have no clue what could be wrong... Nobody else has reported similar issues

**Comment by border999** [comment]
Is it possible that Grimoire of Gaia's version of instant damage is conflicting with yours?

**Comment by McJty** [comment]
That would be weird because my instant damage is just vanilla's instant damage. DR isn't adding any potion effects on its own

**Comment by border999** [comment]
Still, mind looking into it quickly?

**Comment by McJty** [comment]
Well not sure what I can do. I cannot reproduce the problems (and btw, I have used Deep Resonance in combination with Grimoire of Gaia in a personal lets play myself on 1.7.10). Also did you try the command that I gave you? That's about the only thing I can suggest right now

**Comment by border999** [comment]
Didn't use the command but did manage to  get back into my world finally and took some screenshots of the original issue.

**Comment by border999** [comment]
![2016-04-20_17 29 00](https://cloud.githubusercontent.com/assets/11824584/14710994/762f870c-078c-11e6-845e-5628eddbc9ae.png)
Here's where I start with my crystal attempts.

**Comment by border999** [comment]
![2016-04-20_17 31 26](https://cloud.githubusercontent.com/assets/11824584/14711170/2f252064-078d-11e6-9692-238eb0b21bb1.png)
after a few shots from that laser in the corner of the photo. Filled with nether stars as a catalyst.

**Comment by border999** [comment]
And here's the last picture I snapped of it.
![2016-04-20_17 31 37](https://cloud.githubusercontent.com/assets/11824584/14711284/a4363bfe-078d-11e6-83d9-9d27f28b1b68.png)

**Comment by border999** [comment]
Last post for now. I noticed this after I edited my world to move my crystal gear. And I can't pull out of it now.
![2016-04-20_17 58 48](https://cloud.githubusercontent.com/assets/11824584/14711471/48ede034-078e-11e6-97f2-daff9a37375a.png)

**Comment by border999** [comment]
your thoughts?

**Comment by McJty** [comment]
None I'm afraid. I have no clue what is wrong

**Comment by border999** [comment]
for any of the issues?

**Comment by McJty** [comment]
I don't get the last issue? What's wrong in that screenshot?

**Comment by McJty** [comment]
Also does the first issue also happen if you remove the itemduct?

**Comment by border999** [comment]
The last issue is that the crystal thinks it's still being used even when the machine is off. And it refuses to give me anymore of its energy.

**Comment by border999** [comment]
first issue occurs regardless of the conduit being there.

**Comment by McJty** [comment]
There are very weird issues in your modpack for some reason. I have never encountered those and you're the first person reporting them. So no idea what to do about it. Sorry.

**Comment by border999** [comment]
shall I give you a list of my mods?

**Comment by McJty** [comment]
You can do that but not sure how it would help

**Comment by border999** [comment]
how about this, you tell me if you know of any mods that cause issues with yours and I'll check for them on my world.

**Comment by McJty** [comment]
No as I said. I have never heard of this issue before so obviously I have no clue what other mod would cause this. Also it doesn't have to be another mod causing this. I really don't have a clue.

**Comment by McJty** [comment]
The only thing I can suggest is to try to break all DR related blocks and place them again. See if that fixes things. Other then that I'm totally out of ideas

**Comment by border999** [comment]
Now you see why I wanted a complete backport. To see if a more refined version of Deep Resonance might be able to solve this problem.

**Comment by border999** [comment]
update on progress of any kind

**Comment by McJty** [comment]
I am not working on this. I cannot reproduce this and have no clue what the problem could be. Also backporting wouldn't help since this code hasn't changed. Backporting from 1.8.9/1.9 to the 1.7.10 version would essentially result in the same 1.7.10 mod. So I have no clue. Sorry.

**Comment by border999** [comment]
*Sighs*
