### ISSUE TITLE
Bug with launching generator

### ISSUE THREAD

**Issue by Myknakryu** [McJty/DeepResonance#61]
When i make and launch Deep Resonance generator game crashes in modpack. But if i try to recreate crash with only Deep Resonance, game doesn't crash. 

Forge version: 1865

Logs:
http://pastebin.com/KVqzCfyb

**Comment by Myknakryu** [comment]
At the moment I'm checking which mod causes it to happen because in crash log and logs it only says that Deep Resonance is causing crashes.

**Comment by Myknakryu** [comment]
Okay it seems it's only client issue. Because it doesn't crash server it only crashes client when launching generator.

There is crash log of client without other mods:
http://pastebin.com/c6DPuGjN

**Comment by McJty** [comment]
I will check it out soon

**Comment by Myknakryu** [comment]
So, is the bug confirmed???

**Comment by RealGrep** [comment]
Just got the same thing. Same forge (1865). Log file looks the same. Guessing an issue with the sound changes in 1.9, but you'd know far more than I would. :) Let us know if you need more info.

**Comment by McJty** [comment]
I will check this out soon. Probably later today. Busy with rftools atm
