### ISSUE TITLE
Playing about with a 1.9 modpack via Curse and crash on startup

### ISSUE THREAD

**Issue by cauliflower69** [McJty/DeepResonance#62]
http://pastebin.com/mrhtwMn8

**Comment by Xiaminou** [comment]
Can confirm Deep Resonance beta 28 crashes on its own.

Crash Report: http://pastebin.com/VvdYw36V

**Comment by Elec332** [comment]
Yes, this version got pushed before I was notified, so I didnt have time to push the latest ElecCore...

**Comment by McJty** [comment]
Should now be fixed by updating ElecCore
