### ISSUE TITLE
1.9-Crash from radiation effect (NoSuchMethodError) when starting generator

### ISSUE THREAD

**Issue by RealGrep** [McJty/DeepResonance#63]
The radiation effect code seems to be calling a method which doesn't exist, crashing the server as soon as radiation appears. Important lines are:

java.lang.NoSuchMethodError: net.minecraft.util.registry.IRegistry.func_82594_a(Ljava/lang/Object;)Ljava/lang/Object;
	at mcjty.deepresonance.radiation.RadiationTickEvent.getPotions(RadiationTickEvent.java:244) ~[RadiationTickEvent.class:?]

The rest of the output from the point of the crash: http://pastebin.com/EAy64KT8

This is with the latest (at this time) deepresonance-1.9.0-1.1.4beta28.jar and ElecCore-1.9-1.4.266.jar. Running Forge version 1865.

**Comment by McJty** [comment]
I will check it out in a moment

**Comment by Elec332** [comment]
What? How?

**Comment by RealGrep** [comment]
That's a good question! Not very knowledgeable about MC modding at all, so I'm swimming in ignorance here. Could it have something to do with this recent change?

https://github.com/MinecraftForge/MinecraftForge/commit/205f5c13c844540000ed41fbc85057cb8de5ab53
