### ISSUE TITLE
break a reasonant crystal causes Minecraft to freeze

### ISSUE THREAD

**Issue by Hypsellis** [McJty/DeepResonance#71]
I create an issue here like you asked. There is a bug when I break a reasonant crystal wich cause Minecraft to completly freeze. There is no any crash report, but I'm obliged to force Minecraft to stop or my game freeze eternally. I tried it only in creative for the time, but it's surely the same in the normal mode. I use the last 1.9 version. I get only that when the bug happens. http://pastebin.com/ysnkg7v2

**Comment by Hypsellis** [comment]
I repost here because this bug still exists and hasn't been solved in the new versions.

I asked me too if the reasonant crystal wasn't a tile entity, because I got similar errors with tile entities, I get the same error when I break an end portal frame with a ender eye inside. I think that Minecraft 1.9 has a serious problem to manage the tiles entities.

**Comment by Hypsellis** [comment]
If it can help you, I get a similar error with the mod building brick, even if here I get more informations about how happens the bug. But maybe the two bugs come from the same problem.
https://github.com/hea3ven/BuildingBricks/issues/66

**Comment by Hypsellis** [comment]
Ok I get a log now with the new version when the bug happens.

[03:17:18] [Netty Server IO #1/WARN]: Catched unhandled exception : [class mcjty.deepresonance.blocks.crystals.ResonatingCrystalTileEntity] java.lang.NullPointerException

This problem is definitely the same than the BuildingBricks one...

**Comment by Elec332** [comment]
Only that line isnt really helpfull, can you give us the entire log?
(Preferably using pastebin)

**Comment by Hypsellis** [comment]
All the log ? ok.... O___o'
Good luck for finding what you want in this mess ^^'
http://pastebin.com/KhwV1WKg

**Comment by McJty** [comment]
For a modder this is exactly the information we need. Thanks :-)

**Comment by Hypsellis** [comment]
I close this issue because I moved it here https://github.com/McJty/DeepResonance/issues/77
