### ISSUE TITLE
[1.9] Client crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [McJty/DeepResonance#72]
crash report: http://pastebin.com/WYQEJNHi

**Comment by McJty** [comment]
Does this crash also occur if you remove the one probe?

**Comment by McJty** [comment]
Also what version of mcjtylib?

**Comment by Xiaminou** [comment]
this happens if I remove TOP: http://pastebin.com/Zsn5f0gK
Mcjtylib 1.8.5

**Comment by Elec332** [comment]
I think that DR has an unintentioned dependancy on TOP

**Comment by McJty** [comment]
Nah it is more complicated then this. We are investigating (cpw and others) and it is a problem with @Optional not handling generics well

**Comment by McJty** [comment]
BTW, Having just TOP and the older versions of mcjtylib, deep resonance and rftools dimensions will work but then of course without the extra features

**Comment by Elec332** [comment]
Heh, "Optional" is an actual user on github :P

**Comment by McJty** [comment]
ah :-)

**Comment by McJty** [comment]
Go back to the older version of RFTools Dimension and Deep Resonance. You can keep RFTools, McJtyLib and TOP. We're waiting for a forge fix

**Comment by Xiaminou** [comment]
it's okay I'm not playing 1.9 at the moment, I was just testing TOP.

**Comment by McJty** [comment]
Should be ok now I hope
