### ISSUE TITLE
[Bug?] Generator stores netagive energy

### ISSUE THREAD

**Issue by RigorMortis13** [McJty/DeepResonance#76]
Hey really good mod as well :).

Description of the bug in my issue in RFTools-Section:
**Builder and Quarry Card Issuse #545**

_greetings Rigor_

**Comment by McJty** [comment]
There must be some weird mod interaction going on in your modpack if you are having these weird issues. I really have no clue where to go look for this and nobody else reported similar issues...

**Comment by Elec332** [comment]
Linking directly for convenience: https://github.com/McJty/RFTools/issues/545

**Comment by McJty** [comment]
That was fixed some time ago
