### ISSUE TITLE
CrashReport

### ISSUE THREAD

**Issue by Rumaruka** [McJty/DeepResonance#79]
http://pastebin.com/2NyAeYPT
With DeepResonance and ElecCore =(

**Comment by McJty** [comment]
Can you tell a bit more about when this occurs? What did you last do?

**Comment by Rumaruka** [comment]
Just start minecraft version 1.9.4 =(

**Comment by McJty** [comment]
Do you still have this problem? I can't reproduce it actually (as you may have seen if you watch my own lets play)

**Comment by McJty** [comment]
Also new ElecCore should work around this problem in any csae
