### ISSUE TITLE
[Suggestion] Change Laser math (no diminishing return)

### ISSUE THREAD

**Issue by Nurdra** [McJty/DeepResonance#84]
With the actual version, the Infusion Laser allways infuse 500mb.
I think thats a bit of a problem or don't work as intended. It's very hard to get exact 500mb in a tank, because a single ore gives 200mb.
The only way now is, 1000mb in 2 tanks, pickup 1 tank or use a valve and pickup the valve (Because it cant be disabled and start mixing up liquid as soon as you pull out). Both ways are impossible to automate.

If you have 6000mb (12*500mb) liquid ore (1 Crystal) with 85% Purity and you use 12 Diamonds the math is correct and the purity goes up to 90% (5% from a Diamand *12 for each 500mb)
If you allready have over 95% purity, the math don't work with more than 500mb of liquid ore.
The laser picks out 500mb from the tank, use the diamand on it (+5%), but if purity is now over 95% and  is caped at 100%. Now the 500mb liquid with 100% purity goes back and get mixed. With every step, the diamand gives less Purity.
After 12 Diamonds you dont get 100% from 95%, its more about 97.5%. Its allmost impossible to get the max values out of a catalyst if you infuse more than 500mb at once. It's like a dimishing return.

**My Suggestion:**
Change the way the infusion work, if there is more that 500mb liquid. Keep all values but infuse the whole tank at once. If there are 1000mb in it, just use the math 5%*500/1000 and add 2.5%.
With this math, its allways possible to get the same values out of the catalyst regardless of the amount of liquid u have.

**Comment by border999** [comment]
This is the kind of thing I wish would be on a back-ported version for 1.7.10!

**Comment by McJty** [comment]
This is all correctly handled. If there is (for example) 600 mb in a tank then the laser will pick out 500 mb, improve that and then insert it back in the tank. It will there be mixed with the 100 mb that wasn't improved. This is exactly how it should be and works as intended.

It really makes no difference. The math is done correctly. You have to think about the laser as if it extracts 500mb, improves that and then mixes that with what remains. It doesn't make a difference if you do it like this or if you would do it with 500mb at a time (because that's exactly what the laser is doing already)

**Comment by Nurdra** [comment]
I know the math is correct, I dont say it's a bug. I just don't like the dimishing return it cause. And we can't smelt 2.5 ore to get the exact 500mb we need for the Infusion.

The only way to get a max value Crystal is split the liquid to 500mb tanks and infuse them. But there is no way to do this without a lot of tanks and pick them up with a pickaxe to split the liquid.

Is that intended?

Way A:
Smelt 30 ore to 6000mb liquid, use 120 redstone and get about 58% strenght.

Way B:
Smelt 30 ore to 6000mb. Fill it to a tank made by 12 blocks. Pick them all up with a pickaxe (now every tank contain 500mb). Infuse them one by one (10 redstone each). Put them all togehter and get a 60% strenght Crystal.

With way B you can get a 100%/100%/100% cyrtal, with way A it's impossible.
That just feels wrong to me.

**Comment by McJty** [comment]
Actually there are some ways to automate this. For example, the valve can be configured to allow exactly a certain amount of liquid in the tank below. So you can very easily configure the valve to only allow 500mb, infuse that with the laser until another valve detects that it is ready and so on

**Comment by McJty** [comment]
But I do understand the problem and perhaps I'll implement the math like you says. Just have to see how easy that would be

**Comment by McJty** [comment]
Next version of Deep Resonance it will operate on the entire tank (for 1.9.4).
