### ISSUE TITLE
Typo in Radiation Suit Description

### ISSUE THREAD

**Issue by Mohron** [McJty/DeepResonance#86]
https://github.com/McJty/DeepResonance/blob/67d55dba740b2102a41d8e42d60a4d1fffcaa763/src/main/java/mcjty/deepresonance/items/armor/ItemRadiationSuit.java#L36

The tooltip says "Every **chest** piece of the radiation suit" and I'm pretty sure you mean "Every piece of the radiation suit"

**Comment by McJty** [comment]
Fixed next version
