### ISSUE TITLE
Purifier doesn't purify sometimes

### ISSUE THREAD

**Issue by cj89898** [McJty/DeepResonance#87]
Setup: https://gyazo.com/9af3f454467f86f5f8d5139ad07ce95f

I use Ender IO conduits to pump liquid into the top tank. I notice that the purifier takes no action at all on the RCL until I break and replace the machine.

Minecraft Version: 1.9.4
Deep Resonance Version: 1.9.4-1.2.0beta35
Forge version: 1.9.4-12.17.0.1968

**Comment by McJty** [comment]
Should be fixed in latest version
