### ISSUE TITLE
Curse downloads wrong ElecCore

### ISSUE THREAD

**Issue by Dragnier** [McJty/DeepResonance#90]
Installing this mod via Curse launcher in 1.10.2 installs the 1.7.10 ElecCore instead of the 1.10 one.

**Comment by McJty** [comment]
Please report to Curse. We have no control over that

**Comment by Dragnier** [comment]
I think this only happens when the required mod doesn't have a version to match the mod which requires it. For example, Deep Resonance being listed as 1.10.2 and ElecCore only having a 1.10 max version. Basically, Curse client is saying that mod A can't rely on mod B due to it not having the same supported Minecraft version. It makes Curse download the most recent "release" file (which for ElecCore is actualy a 1.7.10  update).

Therefore, I probably should mention this to ElecCore instead, since the Curse stuff is probably working as intended.

**Comment by McJty** [comment]
Well curse should download the latest since the 1.9.4 versions of ElecCore are compatible with 1.10 so there is no need to release a 1.10 specific version

**Comment by Elec332** [comment]
Labeled the latest 1.9.4 release to be compatible with 1.10.2, haven't tested it though.
