### ISSUE TITLE
[1.10.2] Crystal state bug

### ISSUE THREAD

**Issue by awilliamson** [McJty/DeepResonance#92]
The Crystal in question was a 100/100/100 crystal. It was on a pedestal, with a generator active on it.

The crystal was broken, whilst active, and on the pedestal. This resulted in the crystal having a permanent glow. Whenever the crystal is placed again in the world, be it raw, or pedestal, it is glowing, and classifies as 'on'. However, when using the generator it will not 'fire' at the crystal. Therefore, the crystal becomes a useless paperweight, incapable of generating power.

There is currently no way I can see to reverse this permanent state other than jumping into and modifying the ~~metadata~~ NBT data attached to the entity.

This was using the 1.10 version of Deep Resonance. Single crystal setup, using 3-long generator whilst in a flat dimension ( for informations sake ).

EDIT: Eventual fix was using NBTExplorer to location the item and set `glowing: 1` to `glowing: 0` as suspected.

**Comment by McJty** [comment]
Fixed next release
